### ISSUE TITLE
Audio problems on Intel NUC i3

### ISSUE THREAD

**Issue by justanickname** [libretro/Lakka#108]
Lakka seems to be forcing digital audio on Intel NUC (i3 model) when it does not work (at least not through HDMI). I had to go to the PC's BIOS (or is it called UEFI?) and manually disable digital audio completely, and then I could at least use the 3,5mm audio port. This was the only way I could get any audio in Lakka. I am not sure whether or not audio works through DisplayPort however.

**Comment by jayp76** [comment]
Hi i have an MSI Probox23 with an Intel H81TI Board.
I also don't have sound. The H81TI Board does not have an optical output. I want to use HDMI.
This is the proc output:
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7e14000 irq 28
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7e10000 irq 29

What do i have to enter in the retroarch config?
audio_device = "hw:0,0" ?
or 
audio_device = "HDMI" ?
or 
audio_device = "HDA-Intel - HDA Intel HDMI"

First one doesnt seem to work.

**Comment by Kivutar** [comment]
Tell me the output of aplay -L please

**Comment by jayp76** [comment]
here you are.

null
    Discard all samples (playback) or generate zero samples (capture)
hdmi:CARD=HDMI,DEV=0
    HDA Intel HDMI, HDMI 0
    HDMI Audio Output
hdmi:CARD=HDMI,DEV=1
    HDA Intel HDMI, HDMI 1
    HDMI Audio Output
hdmi:CARD=HDMI,DEV=2
    HDA Intel HDMI, HDMI 2
    HDMI Audio Output
default:CARD=PCH
    HDA Intel PCH, ALC887-VD Analog
    Default Audio Device
sysdefault:CARD=PCH
    HDA Intel PCH, ALC887-VD Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC887-VD Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers

**Comment by Kivutar** [comment]
Ok, try

    audio_device = "hdmi:CARD=HDMI,DEV=0"

(Don't forget to stop retroarch while you edit the config file.)

If it does not work, try this :

    audio_device = "hdmi:CARD=HDMI,DEV=1"

or

    audio_device = "hdmi:CARD=HDMI,DEV=2"

**Comment by jayp76** [comment]
thank you Kivutar
this one is the correct line for the H81TI Board  audio_device = "hdmi:CARD=HDMI,DEV=0"
I was confuse with that many HDMI devices listed with aplay.

**Comment by Kivutar** [comment]
Ok, I think I can close this then.
@justanickname if you can't fix your sound using the same method, you can reopen the issue.

**Comment by Spider85** [comment]
I have a intelNuc i7 with openelec and Retroarch 1.2.2. But no sound.
When i trie the command "aplay -D hdmi:CARD=HDMI,DEV=0 /storage/2.wav" a sound is playing.
But if i use "hdmi:CARD=HDMI,DEV=0" in the retro arch GUI or CFG file no sound, can somebody give me a hint?

**Comment by Kivutar** [comment]
Did you stop the retroarch service before changing the config file?

**Comment by Spider85** [comment]
i quit before editing the file, i als tried 

aplay -D plughw:1,0 /storage/2.wav

Then the sound play thru 3.5mm, when set sound option to hw:1,0 in cfg the sounds play thru the headphone.
for the HDMI its hw:0,3, bit when giving the play sound command it says "Device or resource busy
"

**Comment by Kivutar** [comment]
You have to do

    systemctl stop retroarch

**Comment by Spider85** [comment]
It says Failed to stop retroarch.service: Unit retroarch.service not loaded. but it is started

**Comment by Spider85** [comment]
I got the solution, it was a option in "openelec"

**Comment by Kivutar** [comment]
Are you sure that you are using Lakka ?
