### ISSUE TITLE
Systems are barely separated

### ISSUE THREAD

**Issue by justanickname** [libretro/Lakka#111]
PlayStation games can show up under the Nintendo DS category, and so on. There is no system separation with saves either.

If for example you have /storage/roms/sfc/Final Fantasy V.sfc and /storage/roms/gba/Final Fantasy V.gba, the save file will have the same name and they will both be saved in /storage/savefiles, and there is a risk they will overwrite each other.

The easiest way to deal with this issue should be to have each system's games in separate folders (/storage/roms/gba, /storage/roms/sfc, etc), and then also put save files in different folders as well (/storage/savefiles/gba, /storage/savefiles/sfc, etc). When Lakka looks for roms, it should then also look for specific (supported) extensions for certain directories.

**Comment by shockdesign** [comment]
Would it just be worth having directory sorting.. i.e. just the

```
title: Nintendo Entertainment System
matches: nes/*
```

And just have some defined directories in the rom directory for each system.
Also to not have cores show up if there are no roms in it's directory.

**Comment by lukasubo** [comment]
The directory sorting seems like it would be really awesome, since right now, adding a single Neo-Geo ROM + the BIOS completely clutters every menu.

**Comment by Kivutar** [comment]
The playlists are being implemented in RA now: https://www.youtube.com/watch?v=LTuiq-bKsts

**Comment by Kivutar** [comment]
The nightly build include RetroArch 1.2, with rom scanning, and well separated systems.
