### ISSUE TITLE
Smartphones as gamepads

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka#127]
Not exactly an issue, but something that will greatly increase portability of Lakka (and Libretro/Retroarch): 
Create a client/server application that will enable one to use any smartphone (iOS/Android) as a WIFI gamepad (great for parties).
There already some available but all of them lack the following:
- Crossplatform client support (either Android OR iOS)
- Crossplatform server support
- Multiplayer

**Comment by duduke** [comment]
Someone went ahead and created this: 
https://github.com/RetroPie/RetroPie-Setup/wiki/Virtual-Gamepad
https://www.youtube.com/watch?v=eH355PU2Eac
It relies on Node JS, is there any way to include NodeJS into Lakka?

**Comment by Kivutar** [comment]
It is possible, but node is too heavy. The only interpreted language we use on the system is bash. We don't ship perl, we don't ship python. Those eat too much ressources. I would not prefer to include a javascript machine in Lakka.

What we could do is coding a native app for iOS and Android that make them declare as bluetooth joypads. There are things like this already https://play.google.com/store/apps/details?id=com.negusoft.ugamepad

You could try it, maybe it already works?

**Comment by Kivutar** [comment]
Network gamepads got implemented in RetroArch.

**Comment by duduke** [comment]
Yes, I've seen the code change: https://github.com/libretro/RetroArch/issues/2486#issuecomment-165782576
Now we only need the client side... :)

**Comment by fr500** [comment]
I just made a basic client (as a libretro core)
I hope someone can make it linux compatible soon.

**Comment by duduke** [comment]
How can I test this?
I don't see a "gamepad" core in the latest retroarch windows nightly.

**Comment by gouchi** [comment]
For now, you need to compile [it](https://github.com/libretro/RetroArch/tree/master/cores/retropad) yourself.

**Comment by Kivutar** [comment]
Is it working now?

**Comment by gouchi** [comment]
Load Core > Start Remote RetroPad ;-)
