### ISSUE TITLE
MAME 2014 is missing from nightlies

### ISSUE THREAD

**Issue by duduke** [libretro/Lakka#140]
Is there any reason that MAME is missing from the nightly builds?
It was last in the 28-Nov build (128MB System file size) but missing from then on....

**Comment by Kivutar** [comment]
So, did you find an alternative solution? If not, tell me and I will compile a nightly including mame and the lastest code for you.

**Comment by duduke** [comment]
I wasn't able to test it yet, as the Dec-28 build is segfaulting on me.
Will let you know.

**Comment by Kivutar** [comment]
From what I can see here, https://github.com/libretro/fba-libretro/blob/master/svn-current/trunk/src/burner/libretro/libretro.cpp#L65 there is a core option to switch the controls, maybe it does what you want?

**Comment by duduke** [comment]
Still battling the nouveau issue. Once i get over it I will test it out.

‏בתאריך יום שלישי, 6 בינואר 2015, Jean-André Santoni <
notifications@github.com> כתב:

**Comment by Kivutar** [comment]
The new nigthlies fixes the nouveau issue:
http://sources.lakka.tv/nightly/Generic.i386/?C=N;O=D
http://sources.lakka.tv/nightly/Generic.x86_64/?C=N;O=D

**Comment by duduke** [comment]
So, I've been playing around with it for the last couple of days (both on my Nvidia ION HTPC and on the RPi).
FBA is indeed somewhat faster on low end devices (RPi), but MAME supports an order of magnitude more games (Konami - are specifically close to heart) and in some with fewer bugs.
I think that MAME2014 should be included in the PC builds but omitted from the lower end builds.

**Comment by Kivutar** [comment]
Ok, I will add it back then, as soon as I manage to compile it (the repo changed, and the makefiles too). Let me commit the new package.mk and mkpkg.

**Comment by duduke** [comment]
Thanks.

**Comment by saitoh00** [comment]
Kivutar can add o port Mame4all reloaded to lakka?

**Comment by Kivutar** [comment]
I can add it, but isn't its compatibility list even worse than the one of FBA?

**Comment by saitoh00** [comment]
No worse performance would be talking about a leap of mame4all with romset 37b5 2000 to mame4droid with romset 139u1 2010.

Mame4droid performance is a dual core processor at 1 GHz and 1GB of RAM (Samsung Galaxy Tab 2-7 ")
100% fps in almost 95% of the titles, there are games such as east data that seem to go better than in Final Burn Mame4all 2.97.35 (of course on the one hand is fine this final burn because it is much most current and eg outrun better in FB)

There are other games like Konami are not going well in the end burn alpha to be altered colors and make the game very annoying experience (Vendetta, The Simpsons), which did not occur in mame4droid.

I think even if it was included in the test plan would be an excellent idea implemented because they can co-exist and complement each other as things where one fails the other has them and vice versa.

I hope it welcomed the idea as there are many games to go are the same as in mamedroid, would add many points. (Also list system is a much more comfortable thing because it is sometimes difficult to know who exactly is a rom by its filename).

Greetings

**Comment by Kivutar** [comment]
But the libretro version of imame4all looks abandonned since 2012

**Comment by hizzlekizzle** [comment]
There's also MAME 2003 (v078), which is less abandoned than imame4all core and still considerably faster than MAME 2010 (v139)

**Comment by saitoh00** [comment]
The last version of mame4droid its march, 27.2015

I think this mod of imame4all have best performance. 

If you can try the latest build of Mame4droid an android device with similar characteristics to Raspberry Pi 2 see for yourself the reason why I have so looking forward to be compiled for Pi and you can use it on it.

**Comment by Kivutar** [comment]
Some progress on MAME 2015: everything compile, but I get this linking error:

    32251 drivers found
    Compiling generated/mame/mame/drivlist.c...
    /home/kivutar/Lakka/build.Lakka-Generic.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-g++ -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse  -MMD -MP -DPTR64=1 -DCRLF=2 -DLSB_FIRST -DFLAC__NO_DLL -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_APIINTCASTS -DNO_AFFINITY_NP -I../../../../../src/osd/retro/libretro-c
    ommon/include -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/mame -I../../../../../src/lib -I../../../../../src/lib/util -I../../../../../3rdparty -I../../../../../3rdparty/zlib -I../../../../generated/mame/layout -I../../../../generated/resource  -O2 -g -m64 -fPIC --pipe -Wno-deprecated-declarations -O3 -fno-strict-aliasing -Wn
    o-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-narrowing -Wno-attributes -Wno-array-bounds -m64 -fPIC -DINLINE="static inline" -x c++ -std=gnu++98 -Woverloaded-virtual  -o "../../../../gmake/libretro/obj/x64/libretro/generated/mame/mame/drivlist.o" -MF ../../../..
    /gmake/libretro/obj/x64/libretro/generated/mame/mame/drivlist.d -c "../../../../generated/mame/mame/drivlist.c"
    Linking mame_libretro.so...
    /home/kivutar/Lakka/build.Lakka-Generic.x86_64-devel/toolchain/bin/x86_64-openelec-linux-gnu-g++ -o ../../../../../mame_libretro.so ../../../../gmake/libretro/obj/x64/libretro/src/mame/mame.o ../../../../gmake/libretro/obj/x64/libretro/src/version.o ../../../../gmake/libretro/obj/x64/libretro/generated/mame/mame/drivlist.o    -march=x86-64 -m64 -s -Wl,
    --as-needed  -fuse-linker-plugin -flto -L. -L../../../../gmake/libretro/release -L../../../../gmake/libretro/release/mame_mame -shared -m64 -fPIC -Wl,--version-script=/home/kivutar/Lakka/build.Lakka-Generic.x86_64-devel/mame-d8f35df/src/osd/retro/link.T ../../../../gmake/libretro/release/liblibco.a ../../../../gmake/libretro/release/mame_mame/libacorn.
    a ../../../../gmake/libretro/release/mame_mame/libalba.a ../../../../gmake/libretro/release/mame_mame/liballiedl.a ../../../../gmake/libretro/release/mame_mame/libalpha.a ../../../../gmake/libretro/release/mame_mame/libamiga.a 
    
    [...]
    
    o/release/libmongoose.a ../../../../gmake/libretro/release/libocore_retro.a -ldl
    `_ZN8attotime5neverE' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in discarded section `.text' of attotime.o (symbol from plugin)
    `_ZN9emu_timer6adjustE8attotimeiRKS0_' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in discarded section `.text' of schedule.o (symbol from plugin)
    `_ZnwmPKciRK9zeromem_t' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in discarded section `.text' of corealloc.o (symbol from plugin)
    `_ZNK12delegate_mfp18convert_to_genericERP22delegate_generic_class' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in disc
    arded section `.text' of delegate.o (symbol from plugin)
    `_ZN16device_scheduler11timer_allocE8delegateIFvPviEES1_' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in discarded section `.text' of schedule.o (symbol from plugin)
    `_ZN9emu_timer6adjustE8attotimeiRKS0_' referenced in section `.text' of ../../../../gmake/libretro/release/libosd_retro.a(osdnet.o): defined in discarded section `.text' of schedule.o (symbol from plugin)
    collect2: error: ld returned 1 exit status
    mame.make:391: recipe for target '../../../../../mame_libretro.so' failed
    make[2]: *** [../../../../../mame_libretro.so] Error 1
    Makefile:910: recipe for target 'mame' failed
    make[1]: *** [mame] Error 2
    make[1]: Leaving directory '/home/kivutar/Lakka/build.Lakka-Generic.x86_64-devel/mame-d8f35df/build/projects/sdl/mame/gmake-linux'
    makefile:840: recipe for target 'linux_x64' failed
    make: *** [linux_x64] Error 2

**Comment by Kivutar** [comment]
The build is fixed now :)

**Comment by stacystacymc** [comment]
Hi guys can mame 2014 & mess be re added to the droid online downloader please? Worked great with nvidia shield!
Got a second box to go install it and cannot add it to my build making some of the newer cave games unplayable 😢
Tried contacting via twitter and even registering on forum but got no confirmation email to make a post.hope this gets re added as vital to my mame hyperspin build 😉

**Comment by Kivutar** [comment]
Hi @stacystacymc , you may want to create your request here https://github.com/libretro/libretro-buildbot/issues

But I think that your problem is this one https://github.com/libretro/libretro-buildbot/issues/5

**Comment by stacystacymc** [comment]
Thanks I posted where you recommended, hoping we get the core back soon as my new install can't use it


Sent from Samsung Mobile on O2

-------- Original message --------
