### ISSUE TITLE
Lakka menu is slow on RPi

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#150]
Found a possible cause for this bug https://github.com/libretro/RetroArch/issues/1341

Another fact: completely disabling the background quad results in a 15fps gain.

**Comment by ProfessorKaos64** [comment]
I can confirm this, just did an install tonight on a Model B

**Comment by Kivutar** [comment]
This bug also affects RPi2

**Comment by blockfeed** [comment]
@ProfessorKaos64 

To disable the background wallpaper, SSH into the device and change the following in /storage/.config/retroarch/retroarch.cfg:

menu_wallpaper = "/dev/null"

You will likely also need to disable "Configuration save on exit" under General Options as well, then restart Retroarch. This setting will revert back to enabled on next load and maintain the blank wallpaper setting.

**Comment by Kivutar** [comment]
This will not improve performance. The image will not be drawn, but the performance issue is in the drawing of the 3d quad, not the texture itself.

**Comment by Kivutar** [comment]
The new delta timing feature in the menu makes this bug less noticeable, but it's still there.

**Comment by Kivutar** [comment]
The menu is less slow since the block text rendering optimization has been added to RetroArch. Almost unnoticeable now.

**Comment by ProfessorKaos64** [comment]
Nice, i'll have to test this later. Thank you

**Comment by Kivutar** [comment]
Fixed.

**Comment by gabsprates** [comment]
How I can disable the 3d quad?

**Comment by Kivutar** [comment]
Go in Settings > Menu > Menu Shader Pipeline, set it to OFF

**Comment by Kivutar** [comment]
Also disable the text shadows, if any

**Comment by gabsprates** [comment]
THANK YOU! haha
