### ISSUE TITLE
Unable to control Lakka with an Xbox 360 wireless controller on RPi

### ISSUE THREAD

**Issue by ClamCaravan** [libretro/Lakka#151]
With the 9th of January build of Lakka, I am unable to control the GUI. GUI reports Wireless receiver and controller are connected. Have tested with two separate wireless receivers (one OEM and a 3rd party version).

**Comment by Kivutar** [comment]
Ok, try to go in the input settings, and bind the Xbox pad to the first user, not the second or third user. Tell me if it works please.
