### ISSUE TITLE
Cubox-i: FBA sound with lags and cuts

### ISSUE THREAD

**Issue by ralias** [libretro/Lakka#154]
I trying some mame roms in FBA and I found some lags and cuts i the sound. I tested with Cadillac & Dinosaurs and SF2. Is something wrong with the roms or maybe I have to set some parameter in the Audio Settings? The FX Sound is working well.

**Comment by Kivutar** [comment]
I confirm this bug

**Comment by Kivutar** [comment]
Fixed by https://github.com/libretro/Lakka/commit/83e7adf3d64788526657ef9733a4050e326c58fc

**Comment by Kivutar** [comment]
On allwinner, if this fix is not enough, you also have to remove EDID detection from uEnv.txt or disable vsync, so FBA will be 60fps instead of 50fps.
