### ISSUE TITLE
Wrong UI drawing

### ISSUE THREAD

**Issue by alexandrevicenzi** [libretro/Lakka#161]
If you turn on BPi without a screen and after boot you plug it the UI gets wrong displayed.

In my case I'm using HDMI and a VGA monitor, so I'm using HDMI to VGA converter.

![img_20150119_233703824](https://cloud.githubusercontent.com/assets/2637672/5825890/d46aa186-a0d5-11e4-9672-3bb57f37c44f.jpg)

**Comment by Kivutar** [comment]
This is an edge case, I don't think we can do anything about it. The UI needs a screen to get a resolution before RA launches. I guess that's the cause of the bug.
