### ISSUE TITLE
Package blueMSX

### ISSUE THREAD

**Issue by leiradel** [libretro/Lakka#166]
I was able to make blueMSX work with Lakka. Besides adding the core, it's necessary to:

1. Copy the Databases and Machines folders from a regular blueMSX distro to the ~/system folder (you can grab blueMSX from http://www.bluemsx.com/)
2. Configure retroarch-core-options.cfg to:

> bluemsx_msxtype = "MSX2+"
> bluemsx_vdp_synctype = "Auto"
> bluemsx_ym2413_enable = "enabled"

I wasn't able to run MSX 1 and 2 games with bluemsx_msxtype set to "MSXturboR" so I set it to "MSX2+"

So far it's working great.

**Comment by Kivutar** [comment]
Packaged fa3b853
