### ISSUE TITLE
Core options etc, only accessible with the XMB menu driver

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/Lakka#169]
Configuration per core is on. Installed `Lakka-Generic.x86_64-devel-20150130130214-r20504-g57a7349` image just today. Where is this option in the Lakka menu driver?

**Comment by Kivutar** [comment]
The Lakka menu driver is going to be removed. We will replace it with XMB in the next release, when XMB will be stable and improved.

**Comment by ProfessorKaos64** [comment]
Ok, thank you very much for the response @Kivutar
