### ISSUE TITLE
Enhancement Request : ROM filtering by letter, sorting options

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/Lakka#170]
I know this is Lakka on top of Retroarch, but just a suggestion.

**Comment by twinaphex** [comment]
Reasonable request yes. I will put it somewhere on my TODO list for the menu system.

**Comment by ProfessorKaos64** [comment]
Thank you @twinaphex , keep up the great work.

**Comment by Kivutar** [comment]
Another way to implement this would be to keep the list flat, but to go directly to the next/previous letter by pressing L1/R1.

**Comment by arananet** [comment]
Maybe a workaround is the posiblity to create a directory tree, for example:

ROMS > NES
                SEGA
                PSX
                N64
                MAME
                ETC.

Then store the directory location into environment variables, you can filter the content to display on each emulator even using the extension as a plus ;)

**Comment by Kivutar** [comment]
The L1/R1 buttons now allow you to switch to the next letter, so I close this. I agree that this is not very visual and intuitive, but it was the easiest way to implement it in the code.
