### ISSUE TITLE
RPi: Normal keyboard doesn't work well

### ISSUE THREAD

**Issue by albnavper** [libretro/Lakka#172]
It seems that a normal keyboard has some issues in some keys. For example, the arrows works ok, but the Intro doesn't work and can do nothing on menus.

**Comment by Kivutar** [comment]
Have you tried the X and W keys?

**Comment by albnavper** [comment]
That's it, sorry!

I couldn't see it on the installation guide and in the obvious tests I didn't test those keys.

Thanks!

**Comment by Kivutar** [comment]
No problem. Closed.

**Comment by biggdogg2800** [comment]
I have same problem. I don't have a joypad at the moment and want to use keyboard. Only the arrow keys work.  Using HP 8350 laptop keyboard ALSO a lenovo USB keyboard.Both have same behaviour.  Only arrow keys and ESC. keys seem to work.  Can't make any Menu selections.
