### ISSUE TITLE
BeetlePSX crashes when loading game images

### ISSUE THREAD

**Issue by jayp76** [libretro/Lakka#174]
BeetlePSX crashes when loading different game images.
Tried iso, ccd and cue formats.

[   11.675091] retroarch[471]: segfault at 0 ip 00007fc22de3ed09 sp 00007fff88f1edf0 error 4 in beetle_psx_libretro.so[7fc22dddc000+9f000]

It's odd that only "klaymen" (japanese Neververhood) is working.

**Comment by Kivutar** [comment]
I got almost all my .cue loading in beetle-psx :o 
See https://www.youtube.com/watch?v=ZFWbEIA7w8Q
What hardware are you using?

**Comment by jayp76** [comment]
Forgot to mention, tested on x86_64.

**Comment by jayp76** [comment]
MSI Probox23 with 4GB Ram, and Intel i3 CPU.

I put the PSX Bios files under "system". Is this correct?

**Comment by Kivutar** [comment]
It's the correct path yes.

Check that you have all the BIOSes https://github.com/libretro/libretro-super/blob/master/dist/info/beetle_psx_libretro.info and that their names and md5 sums match.

Check that your .cue contains the right name for the corresponding .bin.

**Comment by jayp76** [comment]
Bios names and md5 sums are matching.
Also checked the cue files. Nothing wrong with the names.

**Comment by jayp76** [comment]
Seem to be the images.
Beetle PSX should have ccd support but it does not work.
When i convert the ccd images to bin/cue it works mostly.

**Comment by Kivutar** [comment]
Yes, mednafen PSX supports mostly bin+cue files. I was able to launch almost all my bin+cue files so far. I think that further request should be made upstream. I will close this.
