### ISSUE TITLE
GpSP whitescreen

### ISSUE THREAD

**Issue by dasfreak** [libretro/Lakka#177]
Some games (i.e. Pokemon) will result in a whitescreen.

Started with tty retroarch=0 and searched for games_config.txt but couldn't find one.

Similar issue:
https://github.com/petrockblog/RetroPie-Setup/issues/218

Tested on bananapi with newest nightly and working gba_bios (tested with other games).

**Comment by Kivutar** [comment]
I loaded a rom through gpsp-libretro and saw this message: config_path is : /home/kivutar/Jeux/roms/gba/game_config.txt

So I guess you have to take this file https://github.com/libretro/gpsp/blob/master/game_config.txt and put it next to your rom.

**Comment by dasfreak** [comment]
Yes, this works. Thanks!

**Comment by Kivutar** [comment]
Let me close that then. I will tell urukai to document that on the BIOS doc page.

**Comment by twinaphex** [comment]
Can you mention the exact game this still happened with?

Because having that file in your directory should no longer be necessary. If it does, then maybe it's not properly finding the entry of the game in the built-in database.

**Comment by dasfreak** [comment]
Pokemon Feuerrot (D).gba
Pokemon Smaragd (D).gba

The Pokemon games are known for whitescreen errors. It is solved by setting "Flash 128K''

Final Fantasy I & II - Dawn of Souls.gba worked without the list.

**Comment by twinaphex** [comment]
Well I already added Pokemon Emerald (G) to the gba-over list.

https://github.com/libretro/gpsp/blob/master/gba_over.h#L1536

So it should have worked without that game_list.txt file.

**Comment by dasfreak** [comment]
Is it because of the german version?

**Comment by Kivutar** [comment]
The (G) is for german. Can you copy the whole log of RetroArch when launching this rom please? It could show if the core goes through the end of the list without matching the ROM.

**Comment by Cloudbarrage** [comment]
I can't start Pokemon Ruby or Emerald with the standard configurations, but when I change the Config Directory to a path containing the game_config.txt file I can run them.
Would be interesting to know where the default path is pointing to...

**Comment by Kivutar** [comment]
I guess it's pointing to ~/.config/retroarch/
