### ISSUE TITLE
Unable to access command prompt in PC

### ISSUE THREAD

**Issue by vicmarto** [libretro/Lakka#178]
Hello.

I'm following the instructions to get a command prompt in a PC: http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface

When typing "tty retroarch=0" I get an error: "No such file or directory"

Please, look:
![lakka](https://cloud.githubusercontent.com/assets/11044285/6228662/17aa9ffc-b6af-11e4-854b-527a5d03cb01.jpg)

I need to get a command prompt to setup my wifi dongle, and then get SSH access. No ethernet in this machine, sorry.

This is under "Lakka-Generic.x86_64-devel-20150130130214-r20504-g57a7349"

Thanks!

**Comment by Kivutar** [comment]
Look like you removed the whole line. You should not. Just add "tty retroarch=0" to the existing line without removing anything.

**Comment by Kivutar** [comment]
Somebody accessed the command prompt not so long ago, so I guess it was just that.
