### ISSUE TITLE
Handling of .zip files

### ISSUE THREAD

**Issue by RobLoach** [libretro/Lakka#179]
`.zip` files are filed under the first core that supports the file's extension, despite being for a different core. Would there be a way to select directories to be set for each core?

**Comment by Kivutar** [comment]
Yes, this will be fixed in the new menu

**Comment by RobLoach** [comment]
@Kivutar Any tips on where to look to assist in getting this working? Thanks! :+1:

**Comment by Kivutar** [comment]
You need to wait for the next release where this bug will be fixed.
