### ISSUE TITLE
Support for Thrustmaster Dual Analog 4

### ISSUE THREAD

**Issue by rnavarropiris** [libretro/Lakka#185]
I use an XBox 360 controller & a [Thrustmaster Dual Analog 4](http://www.thrustmaster.com/products/dual-analog-4).

The XBox 360 controller is recognized automatically & works perfectly, but nothing happens when I plug the Thrustmaster in.

Note: I would gladly try to do it myself, but I have no idea where to begin...some hint, please? :)

**Comment by Kivutar** [comment]
Hello, our wiki explains how to generate the config file for your joypad, then you can paste it here and we will add it to our repository.

**Comment by rnavarropiris** [comment]
Thanks! I found [the page](https://github.com/libretro/Lakka/wiki/Configuring-Lakka). I'll take a look at it next week
