### ISSUE TITLE
psx gamesound laggy on cubietruck

### ISSUE THREAD

**Issue by cqwer** [libretro/Lakka#188]
I tried to play Tekken 3 and Fifa 2005 on Cubietruck, but the sound is really laggy. In main menu it works well, but after one or two minutes the whole sound gets really laggy and bad. I already tried to change the uEnv.ct (or .txt) and disabled vsync, but that didn't help

**Comment by Kivutar** [comment]
Can you do a test with another TV?
Did you notice any similar issue with the SNES core?
