### ISSUE TITLE
GLSL Shaders

### ISSUE THREAD

**Issue by ochief** [libretro/Lakka#189]
I saw that you recently had a commit to pull the common-shaders package into Lakka. 

https://github.com/libretro/Lakka/commit/624308e0cd8741e6cf88120c2df9c5324a535ae2

My understanding is this is just pulling the CG, CGP shaders which are not compatible with Lakka, or more correctly with Lakka running in KMS/Frame buffer.

Gizmo who I believe does a chunk of stuff for Retropie has converted all of these to GLSL, GLSLP which ARE then compatible with Lakka.  Maybe you could use his package.  I am not sure what the etiquette is with different Github repos but this maybe worth a look.

https://github.com/gizmo98/common-shaders

**Comment by Kivutar** [comment]
I packaged the GLSL shaders, not the CG ones :)
