### ISSUE TITLE
View retroarch debugging output

### ISSUE THREAD

**Issue by garnieretienne** [libretro/Lakka#192]
I'm trying to get the mupen64plus core working on my build (a Generic x64 system) (see https://github.com/libretro/Lakka/issues/138) and was wondering if lakka have a way to see the retroarch logging info to see what append. 

I've tried to change the `ExecStart=/usr/bin/retroarch` line to `ExecStart=/usr/bin/retroarch &> /storage/retroarch.log` in the `retroarch.service` file and rebuilding the package but lakka refuse to start with this config (I'm not familiar with systemd).

**Comment by Kivutar** [comment]
Hello, you can loggin using ssh, and stop the retroarch service, then launch it by hand, and you will get the output in the stdout.

**Comment by garnieretienne** [comment]
If other search for this, I figured out I can use the `journalctl` command with ssh to follow retroarch output:
```console
journalctl --unit retroarch --follow
```

**Comment by infotek** [comment]
I used
systemctl stop retroarch.service ; retroarch -v
