### ISSUE TITLE
Add support for Saitek P480 (Jess Tech Dual Analog Rumble Pad) controller

### ISSUE THREAD

**Issue by toxwa** [libretro/Lakka#195]
input_vendor_id = 3888
input_product_id = 272
input_device = "Jess Tech Dual Analog Rumble Pad"
input_driver = "udev"
input_b_btn = "2"
input_y_btn = "0"
input_select_btn = "8"
input_start_btn = "9"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "3"
input_x_btn = "1"
input_l_btn = "4"
input_r_btn = "6"
input_l2_btn = "5"
input_r2_btn = "7"
input_l3_btn = "10"
input_r3_btn = "11"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+2"
input_r_y_minus_axis = "-2"

**Comment by Kivutar** [comment]
Thanks, I pushed it to the repo, will be in the next nightly.
