### ISSUE TITLE
VGA monitor not being detected

### ISSUE THREAD

**Issue by Willdrick** [libretro/Lakka#197]
I am using an old laptop as an arcade machine. Loved lakka because it boots fast, but it won't detect my monitor connected to a VGA plug.

Specs:
Laptop with nVidia 320m (seems to work fine, games run at decent framerate)
Lakka-Generic.x86_64-devel-20150307205641-r20834-ge8d52d6
CRT Monitor 640x480 @ 59.94hz in portrait (rotate left) orientation.

Issue:
In Video Options -> Monitor Index
I switch the default 0 (auto) to the left once, laptop screen flickers once (forcing laptop screen?)
I switch to the left again, laptop screen turns off for a second, then shows the lakka loco in the middle of the screen, then I appear again in the options menu (not the video options, 1 level higher). The VGA monitor is plugged and powered on and it shows no image whatsoever.

**Comment by Kivutar** [comment]
The last time I tried that with a video projector, it was working fine.I don't know that much how to help you with that, sorry.
