### ISSUE TITLE
Dual Shock 3 lights constantly blinking under bluetooth.

### ISSUE THREAD

**Issue by techtipsta** [libretro/Lakka#198]
I have successfully paired my ds3 with my bluetooth dongle and all works well other than the lights on the controller constantly flashing rather than showing a solid red light for the player.

Is is possible to stop the flashing/blinking and show a solid red light for the controller number?

**Comment by Kivutar** [comment]
Hello, I don't own a DS3 for now so I can't test it. Maybe somebody else could reply to that?

**Comment by Kivutar** [comment]
OK I own a DS3 now. Please try these instructions: https://wiki.gentoo.org/wiki/Sony_DualShock#DualShock_3
They work for me, no more blinking.
