### ISSUE TITLE
Configuration for specific core

### ISSUE THREAD

**Issue by garnieretienne** [libretro/Lakka#199]
Hi, I have a specific joypad I need to setup correctly for only one core (it's a two player arcade pad).

I want the default plug and play behavior with auto config for every core but this one.

I've tried to enable the per core configuration in xmb but if I change a configuration option with the save-on-exit option enabled, it save and overwrite the configuration for every cores. I've found this thread https://github.com/libretro/RetroArch/issues/1541 and a `configdir` option but I've found no documentation about it in the [`retroarch.cfg`](https://github.com/libretro/RetroArch/blob/6db7115484ccb46abb10ba6d823958a890b13e10/retroarch.cfg) comments.

Is this kind of thing possible in retroarch / lakka ?

**Comment by Kivutar** [comment]
Hello, I've never tried per core configs before. If I get it right, the default path for configdir on Lakka is /storage/.config/retroarch/

I suggest you to stop the retroarch service and write those files manually for a cleaner test.
