### ISSUE TITLE
Keyboard Not working /Only Arrow keys and ESC key works

### ISSUE THREAD

**Issue by biggdogg2800** [libretro/Lakka#203]
I don't have a joypad at the moment and want to use keyboard. Only the arrow keys work. Using HP 8530 laptop keyboard ALSO a lenovo USB keyboard.Both have same behaviour. Only arrow keys and ESC. keys seem to work. Can't make any Menu selections. Tried X and W to no avail.  Thank you!

**Comment by Kivutar** [comment]
OK, does anybody else noticed this bug?
I can't really help you if you're the only one facing this issue. On my 3 PCs the keyboard is recognized without problem.

**Comment by tiagoanleite** [comment]
Both my keyboard and my gamepad are working, tho I'm having issues setting up the gamepad.

**Comment by Kivutar** [comment]
Anybody else?
