### ISSUE TITLE
Request: add a shutdown option to the menu

### ISSUE THREAD

**Issue by tiagoanleite** [libretro/Lakka#206]
I'm using Lakka on an old Atom mini desktop computer I had lying around. It's quite frustrating having to force shutdown the computer every time I'm done using Lakka. There should be an option on the menu to safely shutdown the computer. Same with the all the other systems, specially to keep the system from getting corrupted.

**Comment by Kivutar** [comment]
Hello, our latest development builds have a "Shutdown" entry. Please try one from here http://sources.lakka.tv/nightly/ and tell me if you're satisfied with it?

**Comment by ochief** [comment]
That shutdown option works great for me.  It would be nice to have some kind of feedback that its in the process of shutting down but hardly a high priority, it is definitely functional.

**Comment by Kivutar** [comment]
I agree, I tried to display an OSD message but it won't display.

This feature is implemented as a patch. We should rewrite it in RetroArch properly (so it can work on other OSes)
