### ISSUE TITLE
joypad-autoconfig-udev - Mayflash-PS2-SS-N64-to-USB-Adapter

### ISSUE THREAD

**Issue by paalfe** [libretro/Lakka#211]
I have a Mayflash PS2/SS/N64 to USB adapter that I have made joypad-autoconfig-udev for.

One with a genuine Sega Saturn Controller connected.
One with a Hyperkin PS2 Controller connected.
One with a Hyperkin/Cirka N64 Controller connected.

There is a problem, the adapter have the same input_device and vid:pid whatever controller is connected so the config files have the same input_device and vid:pid. 

The button layout is different for each config file.

They are available here:
https://14f5cb0de29aa07b7e2ca468e5d531b7b921461a.googledrive.com/host/0B7lT5q7hw78DakR0QTRXd1MxTnc/

**Comment by Kivutar** [comment]
Hi @paalfe,

They are invisible, just the adapter is detected. So all your config files have the same vid:pid but also the same name...

Sorry but I can't include these files in the repo. It will never work.
