### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#214]
- [ ] Famicom Disk System
 - [ ] Oddyssey 2
 - [ ] Gamepark GP32
 - [ ] Entex- Adventure Vision
 - [ ] ColecoVision
 - [ ] Casio - Loopy
 - [ ] Quake 
 - [ ] RCA Studio II
 - [ ] Doom
 - [ ] Sega PICO
 - [ ] Tiger Game.com
 - [ ] VTech - CreatiVision
 - [ ] Watara Supervision
 - [x] Shader Options
 - [ ] System Information
 - [ ] Database Manager
 - [ ] Cursor Manager
 - [x] Close Content
 - [x] StellaView
 - [ ] Sufami Turbo
 - [x] Image
 - [x] Movie
 - [x] Music

**Comment by sergiobenrocha2** [comment]
It's missing MSX2, is it the same for MSX?

**Comment by Kivutar** [comment]
We should have one icon per rdb, so if we have separate rdb for MSX and MSX2, then we should have 2 separate icons.

**Comment by sergiobenrocha2** [comment]
What's the default or most used media for MSX? The wiki says some MSX models didn't come with floppy, maybe it make more sense use cartridge instead?
http://www.msx.org/wiki/MSX_for_beginners

Some cartridges:
http://www.grauw.nl/msx/imagegallery/

I liked this one:
![msx cartridge](https://cloud.githubusercontent.com/assets/5431285/8558267/692bc9ee-24d9-11e5-8da4-9a596eb0ad7f.jpg)

**Comment by sergiobenrocha2** [comment]
The others may be confused with genesis cartridges.

**Comment by Kivutar** [comment]
Oh I like this one, it is easily recognizable. I have no idea what is the most common media for MSX though :(

**Comment by sergiobenrocha2** [comment]
A already did a PR ;)

**Comment by Kivutar** [comment]
Merged.

A user sent me a Game & Watch icon by mail. I had to fix it a little. Now the problem is I don't know how to name the file.

**Comment by sergiobenrocha2** [comment]
It's missing History list icon yet.

**Comment by sergiobenrocha2** [comment]
Btw, why mame's content icon is a coin (and I needed someone told me it was a coin lol :p )? Would not it be better to use an eletronic chip instead? Or 2 chips?

**Comment by Kivutar** [comment]
Well, that was not an easy choice I admit... The rationnale was that most users ignore that games in arcade are stored on ship. They have never seen an arcade ship of their life. Only arcade specialists and emulator people know that. While the user have in his mind that one game session equal one coin.

**Comment by kerunaru** [comment]
Just for the sake of knowledge… The most common media on MSX systems was the cartridge. :)
