### ISSUE TITLE
Add Zeroplus joypad support

### ISSUE THREAD

**Issue by PieVo** [libretro/Lakka#219]
I have here a "XFX Executioner" with a zeroplus controller in it. This is a kind of PSX controller clone with 2 analogs and lots of buttons. I would love to see it included in the next builds :+1: 

--- a/projects/Generic/linux/linux.x86_64.conf
+++ b/projects/Generic/linux/linux.x86_64.conf
@@ -3179,7 +3179,7 @@ CONFIG_HID_TOPSEED=y
 # CONFIG_HID_WACOM is not set
 CONFIG_HID_WIIMOTE=m
 CONFIG_HID_XINMO=y
-# CONFIG_HID_ZEROPLUS is not set
+CONFIG_HID_ZEROPLUS=y
 CONFIG_HID_ZYDACRON=y
 # CONFIG_HID_SENSOR_HUB is not set

And here's the mapping:
input_device = "Zeroplus PS Vibration Feedback Converter "
input_driver = "udev"
input_vendor_id = 3090
input_product_id = 5
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "11"
input_start_btn = "8"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "4"
input_r2_btn = "5"
input_l3_btn = "9"
input_r3_btn = "10"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+3"
input_r_x_minus_axis = "-3"
input_r_y_plus_axis = "+2"
input_r_y_minus_axis = "-2"

input_b_btn_label = "3"
input_y_btn_label = "4"
input_select_btn_label = "12"
input_start_btn_label = "9"
input_up_axis_label = "D-Pad Up"
input_down_axis_label = "D-Pad Down"
input_left_axis_label = "D-Pad Left"
input_right_axis_label = "D-Pad Right"
input_a_btn_label = "2"
input_x_btn_label = "1"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "Left Thumb"
input_r3_btn_label = "Right Thumb"
input_l_x_plus_axis_label = "Left Analog X+"
input_l_x_minus_axis_label = "Left Analog X-"
input_l_y_plus_axis_label = "Left Analog Y+"
input_l_y_minus_axis_label = "Left Analog Y-"
input_r_x_plus_axis_label = "Right Analog X+"
input_r_x_minus_axis_label = "Right Analog X-"
input_r_y_plus_axis_label = "Right Analog Y+"
input_r_y_minus_axis_label = "Right Analog Y-"

**Comment by Kivutar** [comment]
Thanks, I enabled this as a module here 227da2e
I added your config here https://github.com/libretro/retroarch-joypad-autoconfig/commit/fbffa77656899fb80a19fa1d1407bc0225eadd94

I will be in the future builds. Please re-open this ticket if the next build does not support this pad.
