### ISSUE TITLE
Lakka has some problems when plugging two USB controllers

### ISSUE THREAD

**Issue by marcosps** [libretro/Lakka#228]
Just one of them is active... I also tried to remove and then replug them, and with this tricky way I could make one of then working, and the other was partly working: the r-pad was working nicely, bu then the d-pad wasn't.

There is a way to make both of then to work? Everybody wants to play versus :)

Thanks!

**Comment by alexandrevicenzi** [comment]
What controller are you using?

Could you send the joypad conf (http://www.lakka.tv/doc/Contributing-your-joypad-config/)?

**Comment by marcosps** [comment]
@alexandrevicenzi thanks for the links :)

I'll check right now and then report here if it worked! Thanks again!

**Comment by marcosps** [comment]
Some observations: if I plug first the "DragonRise Inc.   Generic   USB  Joystick   (0079:0006)", enter in a game and after plug my "0810:0001 Personal Communication Systems, Inc. Dual PSX Adaptor", it works.

But, if I start lakka, plug both controllers and after start a game, the DragonRise is not recognized (but I can see a "Port2: Dragon... configured").

is there a way to fix this misbehavior? Please let me now if you need more info.

Thanks!

**Comment by Kivutar** [comment]
I also have a DraginRise controller, and it takes like 1 minute to be recognized (whatever the order of plugging)

**Comment by marcosps** [comment]
hum..

Jean, I`ll try to plug it, and wait one minute to verify if this works!

Thanks!

2015-09-18 3:06 GMT-07:00 Jean-André Santoni <notifications@github.com>:

> I also have a DraginRise controller, and it takes like 1 minute to be
> recognized (whatever the order of plugging)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/Lakka/issues/228#issuecomment-141410177>.
>



-- 
Att,

Marcos Paulo de Souza
Github: https://github.com/marcosps/

**Comment by Kivutar** [comment]
I close this, as I can play with 2 or 3 controllers without problems. This bug may be a controller specific issue, and I don't think we can fix it if it's really the case.

You can reopen this issue if you have more informations.
