### ISSUE TITLE
Menu on Cubox-i is not looking as expected

### ISSUE THREAD

**Issue by oblitum** [libretro/Lakka#230]
I've tried an early Lakka build from May and the menu resembled the screenshots I've seen around, but I just updated the system to the latest `.img` and the menu is looking like the following, is this right?

![20151016_095837](https://cloud.githubusercontent.com/assets/1269815/10542613/c32ea582-73ef-11e5-9780-749aa55fe62c.jpg)

![20151016_095928](https://cloud.githubusercontent.com/assets/1269815/10542608/b40927e4-73ef-11e5-87c4-df5049914331.jpg)

**Comment by oblitum** [comment]
I just get vertical tree access, nothing like the original horizontal menu with the consoles.

**Comment by Kivutar** [comment]
Ah, you are using the development version. Here you have to add content using the add content menu entry. It will generate the lists you need.

**Comment by oblitum** [comment]
@Kivutar Thanks! I'll try it when I get back home and close it if OK =)

An offtopic question, this morning I've tried to shutdown lakka selecting shutdown with the xbox wireless joystick but lakka just freeze on shutdown, I've to unplug it from the wall.

**Comment by oblitum** [comment]
I mean, on clicking shutdown, nothing happens and I can't do anything in the UI.

**Comment by oblitum** [comment]
If this is a non-reported issue I may open another one to register it.

**Comment by Kivutar** [comment]
For me, it takes 20 seconds sometimes, but then it shut down

**Comment by oblitum** [comment]
In my case it didn't, I've wait way more than 20 seconds, will try again when back home.

**Comment by Kivutar** [comment]
In cuboxi, the system fails to close the display. Check if the LEDs of the cuboxi are telling about the shutdown?

**Comment by oblitum** [comment]
Hi @Kivutar, the options I have at "Add Content" don't help, "Download Content" turn the UI irresponsive just like when I get a freeze shutting down, the clock keeps changing but I'm unable to interact with the UI, I may reboot from ssh though. The other options, "Scan Directory" and "Scan File", are empty.

**Comment by oblitum** [comment]
I'd be glad to know how to put this "Content" manually.

**Comment by Kivutar** [comment]
First, transfer your roms to the rom directory.
Then, use the Add Content entry to scan this directory.
Try with super nintendo games.

2015-10-17 10:45 GMT+07:00 Francisco Lopes <notifications@github.com>:

> I'd be glad to know how to put this "Content" manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/Lakka/issues/230#issuecomment-148883470>.
>



-- 
Jean-André Santoni

**Comment by oblitum** [comment]
@Kivutar This worked t show up the consoles! I've copied 3 Mario games for 3 nintendo consoles and the 3 joystick icons shown up. There's still a problem though, when I select a game from this menu, there's the drop down option to Run the game but I can't run it, this option says "No cores available".

**Comment by oblitum** [comment]
@Kivutar Nice, I've run all the updates in the online updater section, "quit RetroArch", and now it's working.
