### ISSUE TITLE
rescanning content create duplicates

### ISSUE THREAD

**Issue by oblitum** [libretro/Lakka#231]
One can have a big issue having a big list of games in `roms` scanned and then ask a rescan of the directory. Duplicates of all roms in there will be created in the main menu, one then needs to delete the playlists files with the duplicates that populate the menu and ask for a rescan from zero. Currently when I have new games, I move the old roms directory to a new one, copy the new games to a empty roms directory, scan it so that only new games get scanned, then move the old roms back.

**Comment by sergiobenrocha2** [comment]
https://github.com/libretro/RetroArch/issues/1908

**Comment by fabioxgn** [comment]
I have the same issue, how do I reset the games list so I can scan again?

**Comment by oblitum** [comment]
@fabioxgn if you have access to the device file structure, you can just remove the playlists directory.

**Comment by oblitum** [comment]
btw, I've generated my playlists "by hand" scripts, because of #232.

**Comment by Kivutar** [comment]
Fixed by https://github.com/libretro/RetroArch/commit/2af07080479cbaf7a8cbb72edb0573c3a2e8172d
