### ISSUE TITLE
core updater for ARM not working

### ISSUE THREAD

**Issue by cudencuden** [libretro/Lakka#234]
using xu3 October 19 2015 build. selecting core updater flashes the screen n nothing happens

**Comment by cudencuden** [comment]
*nothing happens...

**Comment by cudencuden** [comment]
in retroarch.cfg ..i see the two lines below...should core_updater_buildbot_url be blank?

core_updater_buildbot_url = ""
core_updater_buildbot_assets_url = "http://buildbot.libretro.com/assets/"

**Comment by Kivutar** [comment]
You're right.

**Comment by cudencuden** [comment]
I changed to "core_updater_buildbot_url = "http://buildbot.libretro.com/nightly/linux/armhf/latest" about rebooted...but it does the same thing..screen flicker once but nothing happens when i select core updater

**Comment by cudencuden** [comment]
i am opening the \\LAKKA\Configfiles\retroarch\retroarch.cfg with notepad (windows machine) over the network and make the change. then when i restart lakka...retroarch.cfg did not save.....so how are you suppose to make edits to retroarch.cfg? via ssh?

**Comment by cudencuden** [comment]
I'm pretty sure one of the other online update options mess upcore update....because core updater worked when I used it right after fresh install on x64...then I do other online updates n now core updater does not work..same issue as above

**Comment by Kivutar** [comment]
When you edit the configuration file, you have to first stop the retroarch service. If not, retroarch will keep the old configuration in memory, and save it to the file when quitting. Our documentation explain the process to edit that file.

One thing you can do, to start on a clean basis, is stopping retroarch service, backup retroarch.cfg and remove it, start retroarch with that blank config.

From that, if it doesn't work, stop retroarch service, add the right url in the config file, start retroarch again. And see if it works.

**Comment by cudencuden** [comment]
1) ssh into lakka
2) typed: systemctl stop retroarch
3) deleted retroarch.cfg
4) typed: systemctl start retroarch
5) verified blank retroarch.cfg is created
6) systemctl stop retroarch
7) open retroarch.cfg via network share
8) added core_updater_buildbot_url = "http://buildbot.libretro.com/nightly/linux/armhf/latest"
9) systemctl start retroarch 

works now. thanks

**Comment by Kivutar** [comment]
Ok, I need to understand why this value is not here by default then. Thank you for that test.

**Comment by cudencuden** [comment]
hi kivutar...I noticed that everytime I use online updater > autoconfig profile update....I have to quit retroarch for core updater to use the correct url

**Comment by Kivutar** [comment]
Well spotted. Let me declare this on the retroarch tracker, where it has more chances to be fixed.

**Comment by Kivutar** [comment]
The last cores I tried from the buildbot were wrong. pcsx_rearmed was launching, but segfaulted after sometimes.

**Comment by cudencuden** [comment]
so the source files at http://buildbot.libretro.com/nightly/linux/armhf/latest is wrong?

**Comment by fr500** [comment]
those are binaries, not sources

**Comment by Kivutar** [comment]
Yes those are binaries. On beetle-psx, the shadows on 3d models were wrong, and it segfaulted on the title screen of Crash Bandicoot. Maybe an incompatibilité in the optimizations we enabled at compile time?

**Comment by Kivutar** [comment]
Fixed by 4dadcab37a2dd7703e18c81b5add951197a9a7eb

**Comment by xeros** [comment]
Thx for patching it, but now the buildbot should be fixed: https://github.com/libretro/libretro-buildbot/issues/5
