### ISSUE TITLE
Wrong colors with Mame emulation

### ISSUE THREAD

**Issue by guifes** [libretro/Lakka#236]
Almost every game I try to emulate in MAME plays with wrong colors.

**Comment by Kivutar** [comment]
Hello, what hardware are you using? What version of Lakka? and can we get a screenshot? Thank you!

**Comment by guifes** [comment]
Sorry it took me long. The pc @ my workplace. I'm probably running the last version of Lakka, since I downloaded it a few days ago. About the hardware I'll have to check (I'll try and post it here asap with the screenshot as well). But the thing is some games do work perfectly. Almost every game that needs neogeo.zip is not running at all, and I have put neogeo.zip in the rooms folder. (I've put the roms in a directory MAME inside the roms folder would that be a problem?). The games running with wrong colors are TMNT and Simpsons.

**Comment by Kivutar** [comment]
You're using the only mame packaged in Lakka? (the old mame2003) or one downloaded from the Core Updater?

**Comment by guifes** [comment]
I did not download aything besides lakka, and haven't updated anything as well.

**Comment by Kivutar** [comment]
Can you try the core Dinothawr or Nestopia? They use a 32bit color mode. Maybe you graphical card doesn't support this mode. The mame2003 switches to 32bit depending on the game.

**Comment by guifes** [comment]
How exactly do I do that?

**Comment by Kivutar** [comment]
Just load a NES game.

**Comment by Kivutar** [comment]
@guifes any update on this? (Please re-open the issue when you have tried launching a NES game)
