### ISSUE TITLE
Changing PPSSPP internal resolution without restarting gets monitor blank

### ISSUE THREAD

**Issue by matcarfer** [libretro/Lakka#238]
Changing PPSSPP internal resolution and going back to emulator without restarting gets my monitor blank and forces me to a restart (it didnt happen with previous builds), as a workaround I change the internal resolution, ESC, and then enter again. Hope it gets fixed, because you have no other choice to do a hard reset of the PC.

**Comment by Kivutar** [comment]
I tried yesterday on RPi2, and didn't get the same result.

**Comment by Kivutar** [comment]
Sorry but 4 month later, I'm still not able to reproduce. PPSSPP got updater several times since then.
