### ISSUE TITLE
[pcre] version 8.36 is no longer available -> please update to 8.38

### ISSUE THREAD

**Issue by walterheisenberg** [libretro/Lakka#242]
If you want to compile Lakka, then there is an error with "pcre 8.36". This version is no longer available in the FTP: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/
If you change "8.36" to "8.38" in "package.mk" of pcre then the bug is fixed.

**Comment by Kivutar** [comment]
Thanks you, I will do as soon as possible. I have to rebuild from scratch anyway.

**Comment by Kivutar** [comment]
Done
