### ISSUE TITLE
XBOX ONE controller not working on a20 and rpi

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#243]
A user reported this on IRC.

**Comment by gouchi** [comment]
Even on i386 it doesn't not work.

http://libretro.com/forums/showthread.php?t=5489

**Comment by Kivutar** [comment]
Ok I own one now. So i'm testing it.

**Comment by Kivutar** [comment]
Duplicate of https://github.com/libretro/Lakka/issues/394
