### ISSUE TITLE
ZX Spectrum games do not start on RPi2

### ISSUE THREAD

**Issue by pmlopes** [libretro/Lakka#247]
I've the latest git and once i select a ZXSpectrum game or a ZX81 i get a flashing black screen and back to the start menu.

I've looked in the site and cannot find any place how to look for debug what is happening.

**Comment by Kivutar** [comment]
Yes, the fuse package was broken. It is now fixed in the latest nightly builds.
Be sure to test with many different roms, a lot are not working.
Feel free to reopen this if the problem persists.
