### ISSUE TITLE
Issues logging into retroachievements

### ISSUE THREAD

**Issue by kryptalivian** [libretro/Lakka#253]
I go to user-> get to the portion where you click username and it pops up on my screen saying Username. When I type, it doesn't show any of the characters you've typed. Is there a way to fix this or maybe a file I can edit and input the login credentials myself? Sorry about all the questions lately!

One last thing, It's a Raspberry Pi 2 and the image I used was today's image on the site (12/13/2015)

**Comment by Kivutar** [comment]
I've never tried this feature yet. You can try to enter the values manually by editing retroarch.cfg. Refer to out documentation on how to do this :)

**Comment by kryptalivian** [comment]
I'm sorry, but I've done some searching and not sure what I need to enter in the file. I'm at the file and have it pulled up but im not sure what values need entered before I put in my credentials.

**Comment by kryptalivian** [comment]
Finally got it going! :-)

**Comment by Kivutar** [comment]
Nice, if you want to write a page about this in our wiki, it is open to you ;)

**Comment by kryptalivian** [comment]
I'd be more than happy to! :-)

**Comment by Kivutar** [comment]
Great, I created a page here https://github.com/libretro/Lakka/wiki/Achievements

You can start by explaining what is this feature about, give a link to the retro achievments website, and explain how to use it in lakka.

I really appreciate when users can contribute to the documentation :D

**Comment by kryptalivian** [comment]
It's been submitted. Feel free to make changes.

**Comment by Kivutar** [comment]
Thanks. Your instructions are clear.
