### ISSUE TITLE
ScummVM core crash - rpi2

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#272]
If I load ScummVM from the Main Menu/Load Core, retroarch restart. This issue not happens with the other cores.

**Comment by Kivutar** [comment]
I confirm this bug. Even when working with Lakka's toolchain.

**Comment by Kivutar** [comment]
@twinaphex I get the same issue with the scummvm from the buildbot on any of my arm boards. What is the compatibility of our scummvm core with ARM?

**Comment by Kivutar** [comment]
Upgrading the core fixes the problem. The fix will land in the next update.
