### ISSUE TITLE
Image icon stuck on Gui - rpi2

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#274]
In some condition (I didn't understand how to replicate it), some icon like the white folder or the squared rocket stuck on the GUI. I notice that this happens sometimes if I enter into the retroarch menu in a game loaded from the Load Content menu for a non "traditional" core (GW, 4do...).
I'm using the nightly of 30th december.

**Comment by lollo78** [comment]
![img_20160105_234703](https://cloud.githubusercontent.com/assets/6298682/12129915/ee402834-b406-11e5-981a-df3a4b0b49a1.jpg)

**Comment by Kivutar** [comment]
Yes, this is a very old bug. Sadly, fixing it require a major refactoring in the menu system of RetroArch and nobody want to take the risk to cause hundreads of new bugs to fix this :/

Maybe in the future, when RetroArch becomes very stable, I may start fixing this the right way.

**Comment by Kivutar** [comment]
Won't fix.

**Comment by lollo78** [comment]
o_O
:O 
:-| 
:'(

**Comment by Kivutar** [comment]
Yeah I know... but fixing it means breaking a ton of other stuff in RA. I would rather rewrite the entire menu system than trying to fix that.
