### ISSUE TITLE
Neo Geo Pocket Game Suport on RPi 2

### ISSUE THREAD

**Issue by floreal** [libretro/Lakka#277]
By adding beetle-ngp to rpi2 meta package

**Comment by floreal** [comment]
Need someone to test it (don't own a RPi2)

**Comment by Kivutar** [comment]
I will test it, thank you.

**Comment by floreal** [comment]
So ? Should I close that issue ?

**Comment by Kivutar** [comment]
Yes. But anyway merging your PR already fixed the issue automagically.
