### ISSUE TITLE
Second Screen Detected but not working

### ISSUE THREAD

**Issue by Lenwo** [libretro/Lakka#288]
I have a notebook with Intel / AMD Hybrid graphics. When I plug in my TV via HDMI, a flower can be seen on TV. The XBMC shows up on the notebook. I can only switch the Monitor Index between 0 and 1, not to 2. Tried it via SSH, but when I change the config to '2', the notebook screen gets black and the flower on the TV stays.

I can not change the screen to the TV, altough it is somehow detected.

**Comment by Kivutar** [comment]
Ok, please try this https://github.com/libretro/Lakka/wiki/PC

**Comment by Lenwo** [comment]
Hi Kivutar,

I have to admit it fixed that problem but I could not find this page. Thanks for your help!

**Comment by Kivutar** [comment]
No problem :)
