### ISSUE TITLE
Question: Atom-based support

### ISSUE THREAD

**Issue by gbraad** [libretro/Lakka#289]
How about Atom-based boards as supported platforms?

Atom have an Intel based GPU and have decent performance, especially when compared to some of the ARM-based boards.

**Comment by duduke** [comment]
I have both an nvidia-ion (atom330+gefroce9400m) and an old atom 230. It is supported and works.

**Comment by Kivutar** [comment]
The generic image should work on those boards, if they have a BIOS.

**Comment by LukasBombach** [comment]
I'm getting 0.0 fps on a [Foxconn nT-535](http://www.foxconnchannel.com/ProductDetail.aspx?T=NanoPC&U=en-us0000006) with a Intel NM10 CPU / Intel Graphics Media Accelerator 3150, which seems kind of odd as Lakka runs smoothly on a much weaker Raspberry Pi. Not sure if it needs a graphics driver or something like that, but it runs like that "out of the box" after a new install.

**Comment by duduke** [comment]
According to this: https://wiki.gentoo.org/wiki/Intel (look under Gen3) I believe that GMA3150 only supports OpenGL 1.5 whereas RetroArch needs atleast OpenGL 2.
P.S. the RPi has OpenGLES 2.0 which is mostly similar to desktop OpenGL 2.

**Comment by LukasBombach** [comment]
That must be it, thank you!
