### ISSUE TITLE
[request] add support for various formats of pictures and their auto fit and resize for wallpapers

### ISSUE THREAD

**Issue by lir448** [libretro/Lakka#290]
I can put a picture in the device's file system and set them as wallpaper in the menu settings, but:
 
1. The system recognizes .png only and not adjusts the image to the screen correctly. The image is not properly stretched if it's 21:9 and the screen is 16:9.
2. If I chose the picture as wallpaper in the settings menu, I can not remove it and return to the normal desktop. I think that such adjustment would be useful.

**Comment by Kivutar** [comment]
1. Thanks, this feature request would have its place in RetroArch issue tracker more than here.
2. Use the start key on the setting entry.
