### ISSUE TITLE
Ugly menu

### ISSUE THREAD

**Issue by Fransebas** [libretro/Lakka#308]
hi, I recently install lakka from the nighties, it was the i386 of 2015/08/06 because when I install the one from the download section it never turn up, but this version is working perfectly except for the menu wich isn't the one from the ones I see on the internet and the web page. I try to update from the newest and when I did my computer doesn't even turn on, it only reboot and do strange noises right after it load lakka, but I load the previous version and work fine. Is there a way that I can download only the menu driver?
the menu its only two gears and there is no left and right icons I have to manualy select the rooms and the BIOS.

**Comment by Kivutar** [comment]
Hello Fransebas, looks like you were using a very old version. 

I have no idea why the new version doesn't work for you... Especially those strange noise your talking about, it's the first time a user report such a bug.

Can you send me a photo of this menu with two gears please?

**Comment by Fransebas** [comment]
![img_7452](https://cloud.githubusercontent.com/assets/16038053/13552554/f7deb238-e32d-11e5-9003-45fce1be4330.JPG)
This is the image, and the problem with the other version, I believe, is the hard drive and some noise it made when restart, I'm using a dell pavilion 2006 32 bits

**Comment by Kivutar** [comment]
Ok, the version I see here on your photo is kind of old!

However, you should be able to add icons on the right using the **Add Content** entry to scan directories of roms.

Does your dell have an ATI graphic card?

**Comment by Fransebas** [comment]
The add content work thanks! but didn't detect the atari and MAME game. The computer is a inspirion 1525, integrated Intel GMA X3100 graphics

**Comment by Kivutar** [comment]
Hello, Atari and MAME games are not yet scannables. But there are some scripts on our wiki and forum to workaround that problem, while we implement this fonctionnality.

**Comment by Kivutar** [comment]
@Fransebas what is your hard drive?

**Comment by Kivutar** [comment]
I close this since I don't get any reply.
