### ISSUE TITLE
RGUI - No option to shutdown or restart‏

### ISSUE THREAD

**Issue by jamesclarke555** [libretro/Lakka#311]
I'm using an old CRT for Lakka on a Pi 2. I use the old RGUI menu driver as its more suited to my needs, but the option to shutdown or restart is removed, only quit retroarch is available.

**Comment by Kivutar** [comment]
I pushed a commit in RetroArch. I think it landed in Lakka nightly builds.

**Comment by jamesclarke555** [comment]
Brilliant, thank you very much Kivutar.
