### ISSUE TITLE
[request] Option "Restore to default settings"

### ISSUE THREAD

**Issue by lir448** [libretro/Lakka#317]
I experimented with the settings and save them in a file by default (retroarch.cfg). And playstation and sega games stopped working after these experiments. I tried to fix it but could not find the cause that has affected their work. I had to format the memory card and install the system and games again. This helped but took a long time to copy the games etc.

I think that the function "Restore to default settings" will be useful for fast system restore to its original state.

**Comment by Kivutar** [comment]
Yes, for this, connect using ssh and

    systemctl stop retroarch
    rm .config/retroarch/retroarch.cfg
    systemctl start retroarch

**Comment by lir448** [comment]
Thanks!
