### ISSUE TITLE
issues with live

### ISSUE THREAD

**Issue by rocketlawnchair** [libretro/Lakka#321]
trying to run a live version on a acer r11. 
after I select live. I get 
*** error in mount_storage: mount_common: could not mount uuid=d428e583-2fea-451d-bc4f-e5788c891daa ***
she can't access tty; job control turned off
#
any helps would be welcomed

**Comment by Kivutar** [comment]
Hello, you just need to redownload/reflash.

It often happens to me too.

Especially when the USB key was already flashed with Lakka.

To avoid that, I always flash two times in a row now.
