### ISSUE TITLE
Amiga emulator

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#331]
I just saw the libretro core version of UAE4ARM emulator.
github.com/r-type/uae4arm-libretro
@Kivutar: have you compiled it and tested?
I know that the non libretro version of UAE4ARM is pretty good; maybe, if the libretro version is fine too  you could add it to Lakka.

**Comment by Kivutar** [comment]
We didn't know it. I will package it, thanks.

**Comment by lollo78** [comment]
Glad to be useful :smile: 
Have you compiled/tested it?

**Comment by escalade** [comment]
I've packaged it in my OE fork. I managed to start a game using a configuration file, but it's extremely buggy and sound is messed up. Definitely a work in progress.

**Comment by Kivutar** [comment]
Ok, I close this for now.
