### ISSUE TITLE
BUG: Cannot use RGUI in latest Pi 2 build (20160319231640-r21378)

### ISSUE THREAD

**Issue by jamesclarke555** [libretro/Lakka#332]
If I select RGUI as the menu driver and quit RetroArch, it's launches back into XMB.

**Comment by twinaphex** [comment]
Lakka might have to update to the latest RetroArch version, it not saving the changes being done to driver settings was a bug in an earlier version from a few days ago, should be fixed now.

**Comment by Kivutar** [comment]
I will update asap.

**Comment by jamesclarke555** [comment]
Thanks guys.
