### ISSUE TITLE
Also Retroarch 1.3.2 freeze with multiple scan

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#333]
With the retroarch binary inside the last Lakka nightly (Lakka-RPi2.arm-devel-20160319231806-r21378-g78af2e1) I tried to scan a lot of roms folder (from No-Intro collection stored on my NAS) at the same time and retroarch Freeze.
To reprocude the bug, start scanning for huge roms collection at the same time: try with Gameboy + Gameboy Advanced + Nintendo 64 + Nintendo + Super Nintendo...
Each of this folder have more than 1000 roms inside. 

EDIT: sometimes the crash occurs also scanning only one folder at a time

**Comment by Kivutar** [comment]
This may be fixed now.

**Comment by Kivutar** [comment]
Looks like it is fixed.

**Comment by patriote91** [comment]
I was able to reproduce this on the XU4 build of 2.0. My board froze when scanning more than 1000-2000 games. If you need any additional information let me know.
