### ISSUE TITLE
[Feature Request] Default support for NESPAD by Xgaming?

### ISSUE THREAD

**Issue by Hedda** [libretro/Lakka#334]
Please consider adding default support for the "NESPAD", which is a new cross-platform gamepad in extended SNES/NES/N64 retro-style combo by Xgaming of X-Arcade fame.

http://shop.xgaming.com/products/nes-wireless-gamepad-ios-android-mac

I know that Shawn Walters <shawn@xgaming.com> from Xgaming donated an Tankstick (XArcade) to developers before and bet they donate NESPADs too if asked ;)

**Comment by gouchi** [comment]
If this gamepad comes from [8bitdo](http://www.8bitdo.com/nes30pro), there are already [autoconfig profiles](https://github.com/libretro/retroarch-joypad-autoconfig/tree/master/udev).

**Comment by Kivutar** [comment]
@Hedda it's not working? Are you using the latest firmware? You're using wired or bluetooth?

**Comment by Redemp** [comment]
This is a rebranding of the 8bitdo Nes30 pro.

I wonder why they did that?

**Comment by Kivutar** [comment]
No reply from @Hedda so I close this for now.
