### ISSUE TITLE
beetle-psx-libretro missing in last Lakka nightly

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#335]
Hi, considering that psx_rearmed will not be supported anymore, could you please add by default the Mednafen beetle-psx-libretro core? Thx

**Comment by Kivutar** [comment]
It's too slow on weak hardware. Who told you that pcsx_rearmed will not be supported anymore?

**Comment by lollo78** [comment]
twinaphex here:
https://github.com/libretro/Lakka/issues/305
> About pcsx rearmed: I don't think we are going to be continuing development on that. There is a large amount of ASM code in there that really cannot be maintained properly and it would just result in continuous laborous maintenance, far better to focus our efforts on Rustation and Mednafen PSX. And for now, ARM isn't a priority there. So you will just have to live with the current state of pcsx rearmed, there is no active development going on it and it makes for a pretty bad foundation for future PSX development as well.

**Comment by Kivutar** [comment]
Yes, that's what he is saying for more than one year. He did a lot of improvements on Beetle PSX, but it's still not fast enough compared to pcsx_rearmed. We still need to wait.

**Comment by lollo78** [comment]
:(

**Comment by Kivutar** [comment]
Don't worry, it's not like pcsx_rearmed was going to disapear :)

**Comment by lollo78** [comment]
In the meantime I opened an issue here: 
https://github.com/libretro/pcsx_rearmed/issues/31
:smile:

**Comment by Kivutar** [comment]
I close it for now since beetle-psx can't run yet on those arm boards.
