### ISSUE TITLE
Rasp Pi 2 - Box Art issue not displaying.

### ISSUE THREAD

**Issue by Strider78** [libretro/Lakka#337]
Hello Everyone,

First of all, I would like to give thanks to everybody in this community for all the hard and all the time spent in this nice project.

I'm a new user to Lakka and I recently bought a RPi2. 

I'm having certain issues on RetroArch (1.3.2) on RPi2 that seems not to be a problem on RetroArch(1.2.2) for Mac for instance the BoxArts not displaying properly on RPi2.

I took some screenshots to better try to explain the issue. 

On my Macbook pro I have RetroArch 1.2.2 installed, and everything works as it should. It displays the boxarts and play most of the games.

These 4 pictures bellow illustrates the RetroArch 1.2.2 on the Mac (BoxArts Displayed correctly)

<img width="953" alt="screen shot 2016-03-23 at 2 31 21 pm" src="https://cloud.githubusercontent.com/assets/18037552/13998520/a9459458-f105-11e5-99e2-41f10999ec75.png">

<img width="959" alt="screen shot 2016-03-23 at 2 34 58 pm" src="https://cloud.githubusercontent.com/assets/18037552/13998540/bef26d30-f105-11e5-954d-d508d535c745.png">

<img width="1440" alt="screen shot 2016-03-23 at 2 09 05 pm" src="https://cloud.githubusercontent.com/assets/18037552/13998550/c367bd16-f105-11e5-9ac0-8e41993dd40c.png">

<img width="1440" alt="screen shot 2016-03-23 at 2 09 14 pm" src="https://cloud.githubusercontent.com/assets/18037552/13998561/c86ba6ec-f105-11e5-93d9-de4235a02c7c.png">

The Issue - The pictures illustraded bellow its for the RPi2 BoxArt issue.

I have the boxart files copied through Samba into RPi2 BoxArt Directory.

<img width="779" alt="screen shot 2016-03-23 at 2 27 35 pm" src="https://cloud.githubusercontent.com/assets/18037552/13998712/9d5f5f06-f106-11e5-9d00-957fe2052742.png">

The boxart files are name properly according to the rom scanning.

<img width="923" alt="screen shot 2016-03-23 at 3 00 07 pm" src="https://cloud.githubusercontent.com/assets/18037552/13999090/a4d6e716-f108-11e5-8fb5-353fb6de5056.png">

I have boxart directory set at:
![img_1822](https://cloud.githubusercontent.com/assets/18037552/13998740/c32d3276-f106-11e5-93e5-6b43f057aa6f.JPG)

I have the display boxart on (enabled)

![img_1823](https://cloud.githubusercontent.com/assets/18037552/13998755/d4627362-f106-11e5-9c4a-521ac76a0381.JPG)

But unfortunately nothing shows on RPi2

![img_1826](https://cloud.githubusercontent.com/assets/18037552/13998772/ea6072e0-f106-11e5-9c3b-280fe99fefdc.JPG)
![img_1827](https://cloud.githubusercontent.com/assets/18037552/13998773/ea71f628-f106-11e5-8dbd-aaaac3bdbe93.JPG)

I also tried restarting the RPi2 to see if the changes would take place. Unfortunately nothing happened.

Can anyone help ? Anyone having any similar issues like mine?  I'm not too technical or comfortable yet on RPi2 but I will read and listen to you all.

Once again thank you!

**Comment by Kivutar** [comment]
Hello, we changed something in that feature. Read there: http://www.lakka.tv/articles/2015/11/26/new-major-version-released/

Anyway, it's going to change again soon, since we are going to provide 3 types of images in packs.

**Comment by Strider78** [comment]
I will wait for a new future release and reinstall from ground up.

Thank you so much for replying so soon.

**Comment by Kivutar** [comment]
No problem. I close this for now.
