### ISSUE TITLE
wont boot after install error "Fixing recursive fault but reboot is needed!"

### ISSUE THREAD

**Issue by repomayn** [libretro/Lakka#345]
Iv just install 32bit lakka on a d2700dc motherboard with an ssd drive has anyone had this problem before? i see its a problem people have on ubuntu?  but couldnt find a solution

Thanks in advance

**Comment by Kivutar** [comment]
Hello, I don't know what happened, never saw that message before. Maybe try reinstalling or upgrading from the USB key?

**Comment by Kivutar** [comment]
No more replies, I close this for innactivity
