### ISSUE TITLE
ODROID C1 - Status

### ISSUE THREAD

**Issue by entr** [libretro/Lakka#348]
More of a question really. Interested if any work is planned towards getting the C1 pass the WIP status and what remains to be done in order to consider it stable?

Thanks.

**Comment by Kivutar** [comment]
Hello @entr 

I received recently some new GPU blobs from hardkernel. But they are incompatible for now (they are meson8 instead of meson6). So for now, nothing new in the C1 land.

**Comment by entr** [comment]
I saw 536ba0e2422ee3f1add2dac4b4646683900dceb7 and just wonder if it's something to be excited about?

**Comment by Kivutar** [comment]
It removes the glitch at the top right corner, but the vsync is still not good.
