### ISSUE TITLE
Lakka won't boot on Banana Pi M3

### ISSUE THREAD

**Issue by Ga1tar** [libretro/Lakka#351]
Banana Pi image won't boot on M3

**Comment by Kivutar** [comment]
Hello, the Banana Pi M3 does not have the same CPU as the Banana Pi. So it is normal if this image doesn't boot on it.

**Comment by Ga1tar** [comment]
What should I do then?

**Comment by Kivutar** [comment]
You can invest in one of the supported hardware, or learn how to compile RetroArch manually on the default OS provided with Banana Pi M3.
