### ISSUE TITLE
No Video on Pi3

### ISSUE THREAD

**Issue by Madad1996** [libretro/Lakka#352]
i just installed the newest .img on my SD and it wont boot.
Red light is on and green light blinks
(raspbian boots just fine with same setup)

**Comment by Kivutar** [comment]
Are you sure you downloaded the right image? People often mistake and download the RPi 1 image instead of the RPi 2.

**Comment by Madad1996** [comment]
Yes i downloaded the right one (Lakka-RPi2.arm-devel)

**Comment by Kivutar** [comment]
Sorry, I have no idea of the cause of the problem then. The RPi2 release have been tested several times on RPi3 this last month.

**Comment by Kivutar** [comment]
Sorry, still not able to reproduce, I close this until you get more informations.
