### ISSUE TITLE
[Question] Where is the GUI code in your repository?

### ISSUE THREAD

**Issue by LukasBombach** [libretro/Lakka#353]
Hey guys,

I really love Lakka and I use it on my TV a lot. I want to use it in an arcade machine that I own too, but the UI does not fit quite to an arcade machine. As a programmer I'd like to play around and mess with the UI a bit (or die trying). I am guessing you wrote a skin for Kodi, is that right? If so, I cannot find the code for that in this repository. Can you help me and point it out?

Thanks
Lukas

**Comment by fr500** [comment]
No it's not a kodi skin, it is RetroArch.
https://github.com/libretro/RetroArch/

**Comment by LukasBombach** [comment]
Ah ok, thanks for clarifying!
