### ISSUE TITLE
Connman on PI2 does not recognize wifi dongle since update.

### ISSUE THREAD

**Issue by leparklez** [libretro/Lakka#358]
After* fresh-installing the new "Lakka-RPi2.arm-devel-20160503155601-r21429-g9e4f0ee" image, my 'TL-WN725N' is not recognizable by it somehow. I then tested with Raspbian, LibreELEC and they work just fine.

**Comment by Kivutar** [comment]
Ok can you give me the details of your wifi dongle please?

**Comment by leparklez** [comment]
Model: TL-WN725N
IC: 8853A-WN725N
FCCID: TE7WN725N
That's all the info written on the dongle itself. If there's something else I could find out about it, give me a hint. Oh, and I think I forgot to mention that the older image of lakka had it working. (the one before this huge new update.)
Thanks! :)

**Comment by Kivutar** [comment]
No problem
