### ISSUE TITLE
Odroid C1 stuck upon first boot

### ISSUE THREAD

**Issue by Ali3n0id** [libretro/Lakka#359]
I've tried the latest oDroid C1 build on your website, it resizes then reboots stuck on '[ OK ] Reached target RetroArch.

Using a Sandisk Class 10 16GB SD card

**Comment by Kivutar** [comment]
OK I test it now.

**Comment by Kivutar** [comment]
Thanks, it was really broken.. I'm uploading new builds.

**Comment by Kivutar** [comment]
http://mirror.lakka.tv/nightly/OdroidC1.arm/Lakka-OdroidC1.arm-devel-20160506175459-r21433-gd38de1c.img.gz

**Comment by Ali3n0id** [comment]
No problem, happy to help!
