### ISSUE TITLE
Black screen on all NES emulators

### ISSUE THREAD

**Issue by BigBrawler** [libretro/Lakka#362]
Lakka-Generic.x86_64-devel-20160507182037-r21434-gd23434f.img
Have disksys.rom tested on Nestopia for windows

Black screen then back to menu. Any ideas? 
By the way SNES works.

Good job so far thanks for Lakka!

**Comment by Kivutar** [comment]
Hello, you have to use NES roms that have headers. Let use the roms from the no intro set of 2016. Not the old ones.

**Comment by BigBrawler** [comment]
Will try it thanks!


On 5/11/2016 1:52 AM, Jean-André Santoni wrote:
>
> Hello, you have to use NES roms that have headers. Let use the roms 
> from the no intro set of 2016. Not the old ones.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/libretro/Lakka/issues/362#issuecomment-218376852>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by BigBrawler** [comment]
Fixed it! You are awesome!

**Comment by Kivutar** [comment]
Lol, glad that it works
