### ISSUE TITLE
Error running mame games

### ISSUE THREAD

**Issue by Fransebas** [libretro/Lakka#364]
I have the last version of lakka i386-2016 running in my computer and runs everything fine except for mame games I run the game on the console and get the following error

# retroarch -L mame2003_libretro.so ~/ROMs/metalSlug/mslug2.zip

241-p1.bin   NOT FOUND
241-p2.bin   NOT FOUND
241-s1.bin   NOT FOUND
sfix.sfx     NOT FOUND
sp-s2.sp1    NOT FOUND
sm1.sm1      NOT FOUND
241-m1.bin   NOT FOUND
000-lo.lo    NOT FOUND
241-v1.bin   NOT FOUND
241-v2.bin   NOT FOUND
241-c1.bin   NOT FOUND
241-c2.bin   NOT FOUND
241-c3.bin   NOT FOUND
241-c4.bin   NOT FOUND

**Comment by cudencuden** [comment]
MAME 0.78 romsets

**Comment by Fransebas** [comment]
@cudencuden do I download the "MAME 0.78 romsets"? and if I do, where do I set it on the system folder or in the same folder as the mame 2003?

**Comment by Kivutar** [comment]
IIRC, MAME doesn't use the system folder, just the roms folder.

**Comment by fr500** [comment]
actually, several mame cores use the system folder, I think 078 included, but not for bioses or anything.

**Comment by Fransebas** [comment]
@Kivutar my mistake mame don't use the system folder, anyway, what's wrong whit the already installed mame_2003? do I need to install in cores another version like mame_2015?

**Comment by Kivutar** [comment]
Maybe you're missing a parent ROM or something like that. You keep the whole set in your roms folder?

**Comment by gouchi** [comment]
You are missing neogeo bios.

**Comment by Kivutar** [comment]
Are you running the mame core from Lakka or from the buildbot/updater?

**Comment by Fransebas** [comment]
I have the neo geo zip in the folder, I think is a problem with the BIOS mame2013, I think I'll download the mame2015 but I don't know if I should install it in the same folder as the other BIOS that I installed manually or in other place

**Comment by Kivutar** [comment]
Don't use the cores from the buildbot, they are incompatible with lakka. Delete everything you have in your cores folder

**Comment by Kivutar** [comment]
@Fransebas any news from this?

**Comment by Kivutar** [comment]
No news, I close it
