### ISSUE TITLE
Menu couldn't display chinese filenames

### ISSUE THREAD

**Issue by 9chu** [libretro/Lakka#369]
It seems those utf-8 character can't be properly decoded.
I also tried to change the default font for menu, but it didn't work.

**Comment by Kivutar** [comment]
Hello, yeah RetroArch doesn't support yet UTF-8. You can redeclare this issue on their tracker.

**Comment by gouchi** [comment]
Please check #2007

**Comment by Kivutar** [comment]
@gouchi are you sure you pasted the right link?

**Comment by bparker06** [comment]
Initial UTF8 support for RetroArch was added last month, but currently it only supports the first 256 codepoints, so just Latin-1. This enables languages like French, Spanish, German etc. but the current method of font rendering makes it difficult to support more, so we're still considering options on how to move forward there.

**Comment by Kivutar** [comment]
Thanks for the chinese translation @9chu
