### ISSUE TITLE
Lakka loses selected sounddevice

### ISSUE THREAD

**Issue by fluffymadness** [libretro/Lakka#386]
On the latest lakka stable (odroid xu4), when I select my usb soundcard in the sounddevice settings, and then I reboot the setting is reset to default.
Maybe this is intended behavior, but this way one always has to choose the default device again after every reboot :/
Can anyone confirm this behavior, if its the same on other hardware too?

**Comment by Kivutar** [comment]
Can you check your retroarch.cfg after the reboot? The key is audio_device
Try to force the saving of the config via "save current config"

**Comment by fluffymadness** [comment]
ok...after save current config it works :)

**Comment by Kivutar** [comment]
So the bug may be a filesystem bug. Or the way we quit retroarch fails to save the setting properly.

**Comment by Kivutar** [comment]
Should be fixed with the latest update
