### ISSUE TITLE
Document the IPS feature

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#387]
useful for game translations

**Comment by Kivutar** [comment]
Finding IPS working on no-intro roms is very difficult anyway

**Comment by Alcaro** [comment]
Most SNES IPS are for headered (pointless 512-byte prefix) ROMs. No-Intro doesn't have headers.

I believe same goes for NES, except the headers there actually contain useful data that need to be in a separate database under the No-Intro model.

Could add a --ips-header=512 flag that subtracts 512 from all offsets in the patch (discarding OOB writes), maybe... but that'd be a separate issue, under the rarch repo.
