### ISSUE TITLE
Unable to install on UEFI-only computer

### ISSUE THREAD

**Issue by maxengel** [libretro/Lakka#389]
I have a Cherry Trail-based Kangaroo PC that only supports UEFI. I have tried the recommended installation paths on Linux, Windows, and Mac, but the target machine never sees the created USB drive. It can see other created bootable media, but it seems that the .img file doesn't work on EFI-only machines.

Also, I am trying the 64 bit version for PC's.

**Comment by Kivutar** [comment]
Hello, I saw a thread on the forums, about somebody compiling Lakka with UEFI support. Is that you?

**Comment by maxengel** [comment]
That wasn't me. I've successfully compiled Lakka for 32 bit and 64 bit systems, but neither boots. FWIW, I'm compiling in Ubuntu 16.04 and using dd to copy the .img to a USB drive.

I tried joining the forums, but never got a confirmation email...

**Comment by pmlopes** [comment]
FYI: I've just downloaded an image from a user in the forum:

http://libretro.com/forums/showthread.php?t=5920&highlight=uefi

And I can confirm that it boots and runs on my intel compute stick, the requirement is to set the UEFI to 32bit (Windows 8.1/10) and disable secure boot.

Maybe it would be nice to have these builds also listed on the website.

**Comment by Kivutar** [comment]
I will start by adding those builds in the nightly script.

**Comment by pmlopes** [comment]
Any updates on this?

**Comment by maxengel** [comment]
I am unable to boot from the EFI issues on my Atom-based Kangaroo PC. The drive is a selectable boot device and has been formatted as FAT with GPT, but when I select it as the boot device, it simply has a single underscore frozen in the top-left.

**Comment by Kivutar** [comment]
Try this http://mirror.lakka.tv/nightly/Generic.i386/Lakka-Generic.i386-devel-20161106232131-r21640-ge218f0f-efi.img.gz

**Comment by maxengel** [comment]
Unfortunately that doesn't work. Does it make a difference if I try installation when connected to a PC monitor vs. a TV? right now I am trying on my monitor.

**Comment by conradportelli** [comment]
I'm in the same boat man I have a kangaroo as well . Same issues and to answer ur question tv or monitor does not matter . I find it so hard to understand why so many ego based images can be booted but not this

**Comment by maxengel** [comment]
It is good to know I'm not alone but really too bad it won't install on the Kangaroo. Have people with Intel NUC's had success?

**Comment by conradportelli** [comment]
I think the nucs have legacy options  and work with either uefi or legacy

**Comment by maxengel** [comment]
So no UEFI-only systems work with Lakka?

**Comment by conradportelli** [comment]
The only one I heard of is the lattepanda which can boot the libreelec versions of lakka .. I tried those and still nothing

**Comment by maxengel** [comment]
Interesting... I'm wondering what the most powerful sub-$100 computer that can run Lakka is. I was hoping the Kangaroo would work.

Also, is this feature still under consideration?

**Comment by conradportelli** [comment]
I'm sure it will work sooner or later I'm not gonna give up

**Comment by pmlopes** [comment]
@maxengel intel compute stick 1 did boot lakka for me with the efi image. This stick has only UEFI support. I haven't tested any new images since the commit after my request above.

**Comment by sammcj** [comment]
Indeed it seems the Lakka image / installer does not have UEFI boot capabilities, quite a shame as the three tablet like devices I have are all locked to EFI boot mode only.

**Comment by cmcginty** [comment]
Trying to book from a Chromebox and I think I'm in the same boat.
