### ISSUE TITLE
Decreased input latency by applying RT patch

### ISSUE THREAD

**Issue by larskj** [libretro/Lakka#402]
Hi,

I would like to help making Lakka even better by getting the input latency from controller input to screen update optimized.

So far I have investigated different things and noticed that patching the kernel used by Lakka with the hard real time patch made it possible to significantly raise the "Frame Delay" setting in RetroArch (for nes games it could be raised all the way to the max value of 15, cutting a whole frame of delay off compared to before).

Being able to increase the "Frame Delay" setting indicates the system has less scheduling jitter, which is also as expected.

A major contributor to it may simply be due to the resolution of the kernel timer to be changed from the usual 300Hz to 1000Hz, but I don't see any reason for not running the hard real time patch so we get the best possible dedicated linux system for RetroArch to run on. Of course there are some throughput trade-offs to be made but for emulation a consistent system with low scheduling jitter must be more important.

What needs to be done is basically:

1. Apply the hard real time kernel patch from https://www.kernel.org/pub/linux/kernel/projects/rt/4.4/ (they have patches for most versions)
2. Configure the kernel with hard real time parameters, 1ms timer, fully pre-emptible kernel etc.

I have opened a pull request with the above changes (apply_rt_kernel_patch_to_linux_4_4_2), which should be ready to be merged in if the changes are acceptable.

So far the RT patch is only applied for generic targets using kernel 4.4.2 and the RT kernel configs only enabled for x64. (32bit version should work as before)

I also have other topics I would like to look into as well:

1. Look into the triple buffering going on in the intel kms driver which I hope can shave off another frame of delay. (triple buffering on/off setting?)

2. Investigate the changes needed in RetroArch to utilize the hard real time kernel properly regarding scheduler priorities etc.

3. Figure out what is going on with all the snes cores on average having two frames of input lag more than all other cores.

Any input is welcome.

Thanks,

Lars

**Comment by Kivutar** [comment]
Thanks for your help on this
