### ISSUE TITLE
missing rv100.so driver

### ISSUE THREAD

**Issue by shawn186** [libretro/Lakka#406]
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] RV100/M6 [Rage/Radeon Mobility Series] [1002:4c59] for IBM Thinkpad R40 Type 2681

**Comment by gouchi** [comment]
@shawn186  please try this build http://static.kivutar.me/Lakka-Generic.i386-devel-20160617200404-r21477-g24eba2c.img.gz

**Comment by Kivutar** [comment]
This one have radeon_dri.so static.kivutar.me/Lakka-Generic.i386-devel-20160618022436-r21477-g24eba2c.img.gz

**Comment by Kivutar** [comment]
Ok, r100 doesn't compile shaders yet.
