### ISSUE TITLE
Recommand etcher to flash?

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#409]

**Comment by gouchi** [comment]
Why not, at least it is multiplatform and they have a [roadmap](https://github.com/resin-io/etcher/milestones).

My only concern is that in my quick test, it was a little slow.

**Comment by cbluth** [comment]
I have used etcher in the past on linux, i like the appimage packaging, very cool.

**Comment by Kivutar** [comment]
It supports img.gz directly

**Comment by Kivutar** [comment]
Done, for Generic
