### ISSUE TITLE
Cannot get lakka pc image to book

### ISSUE THREAD

**Issue by kryptalivian** [libretro/Lakka#410]
I cannot get my Macbook pro 15 2015, or Windows Laptop to detect any of the 3 flash drives I've tried to use(128gb pny, 16gb pny, 64gb transcend). I've tried making image on Windows and Mac. I format the drives to fat32 and use DD or windisk32imager to image the flash drive.

**Comment by Kivutar** [comment]
On my Macbook Air 2013, the image is detected when I press alt during the bootloader.

Have you tried the EFI images from the nightly builds?

**Comment by kryptalivian** [comment]
Nightly build worked for me thanks!
