### ISSUE TITLE
[request] nestopia custom palettes

### ISSUE THREAD

**Issue by MiniSpoon** [libretro/Lakka#413]
Please add more palettes to the nestopia core options. Specifically, I would like to see the Sony CXA2025AS palette integrated.

https://github.com/rdanbrook/nestopia/files/311001/SONY_CXA2025AS.zip

Alternatively, perhaps a way to load custom palettes like the windows builds.
https://github.com/rdanbrook/nestopia/issues/122

Thank you.

**Comment by Kivutar** [comment]
Hello, can you add this request in the issue tracker of nestopia-libretro please?
