### ISSUE TITLE
Mupen64 core crashes

### ISSUE THREAD

**Issue by cbluth** [libretro/Lakka#417]
I am running lakka on a small Intel based 64bit system, and mupen64 core crashes at the same point. I have md5sum'd the ROM to make sure its a good dump, and its good.

Is there a way to only update a certain core, even if that way is manually?

edit: i have included a journalctl log:

Jun 30 06:54:50 Lakka systemd[1]: Started Retroarch.
Jun 30 06:55:33 Lakka retroarch[787]: ReadSpecialSettings: DEFAULT
Jun 30 06:55:33 Lakka retroarch[787]: ReadSpecialSettings: DEFAULT
Jun 30 06:55:33 Lakka retroarch[787]: ReadSpecialSettings: THE LEGEND OF ZELDA
Jun 30 06:55:55 Lakka systemd[1]: retroarch.service: Main process exited, code=killed, status=11/SEGV
Jun 30 06:55:55 Lakka systemd[1]: retroarch.service: Unit entered failed state.
Jun 30 06:55:55 Lakka systemd[1]: retroarch.service: Failed with result 'signal'.
Jun 30 06:55:57 Lakka systemd[1]: retroarch.service: Service hold-off time over, scheduling restart.
Jun 30 06:55:57 Lakka systemd[1]: Stopped Retroarch.
Jun 30 06:55:57 Lakka systemd[1]: Started Retroarch.

**Comment by cbluth** [comment]
Here is a verbose log: https://gist.github.com/anonymous/97daa09189dcf5baee1f97493bd8ae7f

**Comment by cbluth** [comment]
Nevermind, I updated to the latest core, found here: http://buildbot.libretro.com/nightly/linux/x86_64/latest/

and placed it in /tmp/cores/ and it isnt crashing any longer.

**Comment by Kivutar** [comment]
Ok this mean we need to update mupen64plus in our images. I reopen this for now and we will close it when mupen is updated and tested on all platforms.

**Comment by Kivutar** [comment]
I've updated mupen since then http://static.kivutar.me/Lakka-Generic.x86_64-devel-20160710153555-r21519-gd0ce46d.img.gz

Can you try this image and confirm that the bug is gone please?
