### ISSUE TITLE
HDMI on pc

### ISSUE THREAD

**Issue by BrokenHDMI** [libretro/Lakka#419]
Reving an old pc and i get to the bootloader (Where it says run live/install) and if i click on either of those my new 3d tv says mode not supported and my monitor and other tvs just go black. any way you can help me. Also will an orange pi work with retro pi/lakka

**Comment by Kivutar** [comment]
Ok, I'm not familiar at all with 3D TVs. But here are a few questions:

What happen when you use the exact same setting, but another linux distribution?

Have you tried all the settings of your TV to disable 3D?

**Comment by BrokenHDMI** [comment]
yes and ihave the same problem with other monitors and tvs. and on other linux distribution i can run it live but when i install it it goes black/mode not supported

**Comment by cbluth** [comment]
@BrokenHDMI 
What happens when you use a Live USB of Ubuntu 16.04 LTS on the same hardware, does the hdmi work when you do that?

**Comment by BrokenHDMI** [comment]
yes it works fine

**Comment by BrokenHDMI** [comment]
Yes it works fin clbuth

**Comment by Kivutar** [comment]
Could be related to https://github.com/libretro/Lakka/issues/365

**Comment by jonny555** [comment]
I have lg 3d tv 2016 I'm it's more than likely your hardware motherboard or drivers or use a different hdmi not 4k 3d arc one

**Comment by Kivutar** [comment]
Any news on this? Did you try another cable?

**Comment by Kivutar** [comment]
No news, I close
