### ISSUE TITLE
Broken CHD support in Lakka's MAME 2003 core

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka#421]
Attempting to load any games which use a CHD results in this error:
`blitz.chd NOT FOUND`
`ERROR: required files are missing, the game cannot be run.`
`RetroArch [ERROR] :: Failed to load content.`

This error isn't present in the version of the MAME 2003 core currently available from the buildbot. 

The issue I'm describing started as a mame2003-libretro issue, which turned out to be a combination of this problem and a more tricky regression in CHD support. If you are interested in that issue: https://github.com/libretro/mame2003-libretro/issues/38

**Comment by Kivutar** [comment]
What if I update mame2003? Would that fix the problem you think?

**Comment by markwkidd** [comment]
I believe so.  Whatever version of that core the buildbot is making for
Linux x64 seemed to fix the issue and be otherwise working well.  I just
did quick spot checking though.
On Jul 2, 2016 2:10 PM, "Jean-André Santoni" <notifications@github.com>
wrote:

What if I update mame2003? Would that fix the problem you think?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libretro/Lakka/issues/421#issuecomment-230114821>, or mute
the thread
<https://github.com/notifications/unsubscribe/ASphdl0ICN-W4uNxemcpmVa1uYEKqpZfks5qRqmDgaJpZM4JDr-q>
.

**Comment by Kivutar** [comment]
Try this build, it have an updated mame2003 http://static.kivutar.me/Lakka-Generic.x86_64-devel-20160710153555-r21519-gd0ce46d.img.gz

**Comment by markwkidd** [comment]
Thank you! I tried that build and it is loading CHDs correctly. That seems to have resolved this issue.

**Comment by Kivutar** [comment]
Thanks
