### ISSUE TITLE
FFMPEG support for wav files

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/Lakka#433]
This is a feature request to allow the FFMPEG core to be able to play wav audio files.

(Note - let me know if I should move this to the retroarch project issues list instead.)

Currently they are not allowed to be played from the frontend (they aren't included in the supported file types). 
Additionally, when trying to play a wav file from the command line (via `retroarch -v -L /usr/lib/libretro/ffmpeg_libretro.so roms/audio_file.wav`) it results in erroneous/grinding loud audio playback.

Below is a log of what happens when attempting to play a wav file:

RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Features:
Built: Mar 19 2016
RetroArch [INFO] :: Version: 1.3.2
RetroArch [INFO] :: Git: 78af2e1
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Config: loading config from: /storage/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Overrides: no core-specific overrides found at /storage/.config/retroarch/FFmpeg/FFmpeg.cfg
RetroArch [INFO] :: Overrides: no game-specific overrides found at /storage/.config/retroarch/FFmpeg/a2002011001-e02.cfg
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [INFO] :: Remaps: core name: FFmpeg
RetroArch [INFO] :: Remaps: game name: a2002011001-e02
RetroArch [INFO] :: Remaps: remap directory: /storage/remappings
RetroArch [INFO] :: Remaps: no game-specific remap found at /storage/remappings/FFmpeg/a2002011001-e02.rmp
RetroArch [INFO] :: Remaps: no core-specific remap found at /storage/remappings/FFmpeg/FFmpeg.rmp
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Up" => "Seek +60 seconds"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Down" => "Seek -60 seconds"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Left" => "Seek -10 seconds"
RetroArch [INFO] ::     RetroPad, User 1, Button "D-Pad Right" => "Seek +10 seconds"
RetroArch [INFO] ::     RetroPad, User 1, Button "L" => "Cycle Audio Track"
RetroArch [INFO] ::     RetroPad, User 1, Button "R" => "Cycle Subtitle Track"
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: XRGB8888.
Input #0, wav, from 'roms/a2002011001-e02.wav':
  Duration: 00:00:54.31, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
RetroArch [INFO] :: Environ GET_VARIABLE ffmpeg_temporal_interp:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ GET_VARIABLE ffmpeg_color_space:
RetroArch [INFO] ::     auto
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 44063.25 Hz.
[SWR @ 0x74000480] Input channel count and layout are unset
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/5xbr-retro.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/bead.glsl"
RetroArch [INFO] :: [SWR @ 0x74000480] Context has not been initialized
Found shader "/usr/share/common-shaders/blinky.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/pixellate.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/quilez.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/retro-v2.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/scanline.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/sharp-bilinear.glsl"
RetroArch [INFO] :: Found shader "/usr/share/common-shaders/stock.glsl"
[SWR @ 0x74000480] Context has not been initialized
RetroArch [INFO] :: Video @ 960x720
[SWR @ 0x74000480] Context has not been initialized
RetroArch [INFO] :: Starting threaded video driver ...
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
RetroArch [INFO] :: [EGL]: EGL version: 1.4
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1360x768.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: OES_texture_npot => exists
RetroArch [INFO] :: Querying GL extension: BGRA8888 => exists
RetroArch [WARN] :: [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
RetroArch [INFO] :: Querying GL extension: GL_EXT_unpack_subimage => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_sRGB => doesn't exist
RetroArch [INFO] :: GL: Using resolution 1360x768
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [GL]: Using GLSL shader backend.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
RetroArch [INFO] :: [udev]: Plugged pad: Microsoft X-Box 360 pad (045e:028e) on port #0.
RetroArch [INFO] :: Autodetect: 106 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /tmp/joypads/udev/Microsoft_X-Box_360_pad.cfg
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 16 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/storage/.config/retroarch/content_history.lpl].
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
[SWR @ 0x74000480] Context has not been initialized
^C[SWR @ 0x74000480] Context has not been initialized

**Comment by Kivutar** [comment]
For your info, there is also an ffmpeg core built in retroarch that can play wav files, iirc.

**Comment by hooby3dfx** [comment]
Thanks, it sounds like this is then a bug with the Lakka ffmpeg core/config.

**Comment by Kivutar** [comment]
@twinaphex and @gouchi, should we remove the ffmpeg core in favor of the backed in one?

Is the backed in ffmpeg compatible with playlists?

**Comment by gouchi** [comment]
@kivutar I think the baked in one is more updated.

I don't know if the builtin is compatible with playlists.

**Comment by hooby3dfx** [comment]
BTW, I noticed that wav files actually do show up in the GUI (Select file and detect core) to be played by the ffmpeg core, so I think this should be labelled as a bug since they cannot be played correctly.

**Comment by Kivutar** [comment]
Can you try these builds with the builtin ffmpeg core of RA? http://sources.lakka.tv/nightly/

**Comment by hooby3dfx** [comment]
I tried the latest (20160811145614-r21565) and the issue is still there.

**Comment by Kivutar** [comment]
Using the builtin player or the external core? Let try the builtin one, use Load Content Detect Core.

**Comment by hooby3dfx** [comment]
I believe that is what I did.
Is the external core even present in that build?

**Comment by Kivutar** [comment]
Yes.. then it also affects the builtin core.. :/

**Comment by hooby3dfx** [comment]
Which means it is a retroarch issue? 
(5 mins later)
I reproduced the issue in retroarch - I can create the bug report there.
