### ISSUE TITLE
Missing some items from online updater in pc latest build

### ISSUE THREAD

**Issue by jonny555** [libretro/Lakka#437]
Hi missing items in online  updater  build 17 July 
Assets
Cores 
Database updaters are missing

**Comment by fr500** [comment]
On Lakka those are meant to be handled with Lakka updates instead of the
core updater

**Comment by jonny555** [comment]
Hi sorry I mean the items aren't listed at all go to online updater  the only two options are update lakka and update thumbnails rest is missing

**Comment by cudencuden** [comment]
this is by design...you can only update lakka n thumbnails...

anything that is missing our needs updated will be done through updating lakka

**Comment by jonny555** [comment]
I'm confused now so you don't use the online updater to get cores and update cores anymore through lakka xmb menu anymore

**Comment by cudencuden** [comment]
........to get updated core...you use "update lakka" option......to update assets...you use "update lakka".....to update database...again, you use "update lakka" option....

**Comment by Kivutar** [comment]
Yes, this is by design. This ensures that there is no inconsistency between the different components.
