### ISSUE TITLE
PSP core crash

### ISSUE THREAD

**Issue by duramato** [libretro/Lakka#443]
Version: http://img.cla46.com/up/1469410120334eace.jpg 
When trying to run Gran Turismo on the psp core, ppsspp, it crashes after the game's boot/inital video right before reaching the game's main menu.

Logs from boot to crash: https://gist.github.com/duramato/20bd6619213d0b749b11dd3d923527fc

**Comment by markwkidd** [comment]
I just wanted to connect this bug report to this broader request that should solve the problem: https://github.com/libretro/Lakka/issues/442

If the PSP core has stopped crashing on you now, you may want to close this ticket though.

**Comment by Kivutar** [comment]
Do you have the font in the system dir?

**Comment by Kivutar** [comment]
No reply, I close the issue
