### ISSUE TITLE
Help lakka caught in flower fabric

### ISSUE THREAD

**Issue by Dallignaantonio** [libretro/Lakka#445]
I am new to this subject and I can not install lakka tried these two (Lakka - Generic.x86_64 -devel- 20160710153555 - r21519 - gd0ce46d and Lakka-Generic.i386-devel-20160607151328-r21464-g936bd6d). After all installation it hangs in the flower display. so something happens to turn off the PC. appears following error message failed unmounting / flash.
Please help me

**Comment by TheDcoder** [comment]
It might be an incompatibility with your PC or your PC's BIOS. We need more information, what OS do you use?

**Comment by Dallignaantonio** [comment]
I had installed windows xp there formated hd to put lakka

**Comment by TheDcoder** [comment]
ok, did you try running lakka in live mode?

**Comment by Dallignaantonio** [comment]
the same thing happens it hangs in Flower fabric

**Comment by TheDcoder** [comment]
Hmm... Do you have Legacy mode enabled in your BIOS?

**Comment by TheDcoder** [comment]
It differs from computer to computer, a little googling might help! also, check your computer/motherboard manufacturer's documentation about your BIOS, it might contains useful information.

**Comment by gouchi** [comment]
Try to connect to lakka command line interface to get some [log](http://www.lakka.tv/doc/FAQ/#how-do-i-debug-retroarch)  provide the output of 
`lspci -nn | grep VGA`

**Comment by gouchi** [comment]
Do you reproduce the issue with [latest nightly ](http://mirror.lakka.tv/nightly/Generic.x86_64/Lakka-Generic.x86_64-devel-20160811142524-r21565-gc79651a.img.gz)?

**Comment by Kivutar** [comment]
No news, we close
