### ISSUE TITLE
Dreamcast core crash (Reicast)

### ISSUE THREAD

**Issue by r6turboextreme** [libretro/Lakka#447]
The Dreamcast core crashes upon loading a game. I used a .cdi file of the game Silver. Lakka does crash, it needs a power cycle. I use the latest Lakka 64-bit version (17 July I believe) Any idea how to solve this?

PC SPECS:
- Core 2 Quad Q8200
- Nvidia GT 220
- 7GB RAM
- 250GB HDD

Thanks

**Comment by markwkidd** [comment]
Is there any way you can get a system log of the crash to post here?

There are some partial instructions on how to access the log here: https://github.com/libretro/Lakka/wiki/Troubleshooting-Lakka

**Comment by Yqnn** [comment]
I have a same issue on a Core i5-4258U, with 2 different cdi files.
`RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: null: [/storage/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
context_reset.
Linux paging: 00001000 00001000 00000FFF
RetroArch [libretro INFO] :: Verify Failed  : ftruncate(fd,RAM_SIZE + VRAM_SIZE +ARAM_SIZE)==0
 in _nvmem_alloc_mem -> core/hw/mem/_vmem.cpp : 591 
DEBUGBREAK!`

**Comment by Yqnn** [comment]
It was an issue with the bios, I fixed it by moving the bios file to system/dc, as described here : https://github.com/libretro/Lakka/wiki/ROMs-and-BIOSes .

**Comment by markwkidd** [comment]
It sounds like your situation is related to this one: https://github.com/libretro/Lakka/issues/442

If everything is working now, you might want to close this issue though.

**Comment by Kivutar** [comment]
So it's just a permission problem on the dc folder?

**Comment by markwkidd** [comment]
I know I'm butting in here, but I've seen a couple of people struggle with this on the forum too. 
This core seems to be tripping users up because instead of putting the Dreamcast BIOS files directly in the system folder, they need to create a subfolder and put the two BIOS files there instead.

This is similar to the PSP core issue ( https://github.com/libretro/Lakka/issues/441) , but I don't think this one also involves a permissions problem with the new folder unless @Yqnn says differently.

**Comment by Kivutar** [comment]
Can I close this now?

**Comment by Yqnn** [comment]
From my point of view, yes.
But I don't know if @r6turboextreme issue was the same as mine.

**Comment by r6turboextreme** [comment]
Yes. This issue can be closed - as I have no time right now to test it, but some possible solutions are shown. I'll test it in three weeks. If this does not work yet, I'll reopen this. Thanks!
