### ISSUE TITLE
Ghouls 'n' Ghosts / Daimakaimura

### ISSUE THREAD

**Issue by mpdt** [libretro/Lakka#452]
As of right now, this game loads properly and the attract sequence plays fine, however it crashes/resets back to desktop whenever I attempt to "insert a coin" using either the Xbox 360 wired pad or using the 5 key on a keyboard.

I have tried a 0.78, 0.139 and 0.37b5 rom, all of them have the same issue.  I have not altered any of the default settings for this game or MAME in general.

Cheers.

**Comment by Kivutar** [comment]
What exact core are you using?

**Comment by Rocklima2** [comment]
Use fba-next working perfect i have this rom

**Comment by mpdt** [comment]
Hi Kivutar, sorry for the delayed response - I was using mame 2003, the default mame driver in the latest download version.

**Comment by mpdt** [comment]
Thank you for the tip Rocklima2, I shall give that a try! :-)

**Comment by Rocklima2** [comment]
Capcom and neo geo games fba-next is best option

**Comment by Kivutar** [comment]
Can we close this report now?
