### ISSUE TITLE
Missing Lakka Services menu entry

### ISSUE THREAD

**Issue by webmaster-gostec** [libretro/Lakka#462]
Yesterday I've installed the last nightly on my Raspberry Pi2:
Lakka-RPi2.arm-devel-20160807205317-r21557-gd292da5.img.gz
To be on the safe side, I've reflashed everything.

After booting I noticed the Lakka Services menu entry was missing.

I've tried purging retroarch.cfg through SSH with the following commands:
`systemctl stop retroarch`
`rm .config/retroarch/retroarch.cfg`
`systemctl start retroarch`
but it ditn't fix.

Maybe something to do with HAVE_LAKKA macro?

**Comment by Kivutar** [comment]
Thanks, I will try to fix this asap.

**Comment by Kivutar** [comment]
Should be fixed in the latest update
