### ISSUE TITLE
Flower Screen

### ISSUE THREAD

**Issue by alexandrebfaust** [libretro/Lakka#465]
**My Lakka not working...**

Only is flower screen, I can select Installer or Live 

I tried two modes

![13819284_528670927337453_874838407_n](https://cloud.githubusercontent.com/assets/12604329/17686942/25383490-6347-11e6-9f63-3486432eacd1.jpg)

**Comment by gouchi** [comment]
Please can you provide some [logs](https://github.com/libretro/Lakka/wiki/Troubleshooting-Lakka).

The more information we will have, the easiest it will be to help you.

Thank you.

**Comment by alexandrebfaust** [comment]
Is it?


![2016-08-16 06 07 07](https://cloud.githubusercontent.com/assets/12604329/17693987/1037a464-6378-11e6-950c-01faa289b6b7.jpg)
![2016-08-16 06 07 46](https://cloud.githubusercontent.com/assets/12604329/17693988/103c69d6-6378-11e6-84f0-53451a66a5dd.jpg)

**Comment by gouchi** [comment]
Thank you, it doesn't seem to have fatal error.

Can you provide the output of 
`lspci -nn | grep VGA`

You are using which video output on which hardware ?

**Comment by Kivutar** [comment]
Are you using two monitors?

**Comment by alexandrebfaust** [comment]
I'm using a notebook without screen
cce win wm545b
![2016-08-16 22 55 33](https://cloud.githubusercontent.com/assets/12604329/17722105/0a1b5164-6406-11e6-9567-87f420d3c03f.jpg)
![2016-08-16 23 01 58](https://cloud.githubusercontent.com/assets/12604329/17722106/0a1d5d74-6406-11e6-94fa-9547e522646f.jpg)

**Comment by gouchi** [comment]
Try to change [video_monitor_index](https://github.com/libretro/RetroArch/blob/master/retroarch.cfg#L149) in the [configuration file](http://www.lakka.tv/doc/Configuring-Lakka/#using-the-command-line-interface) as it seems you are not using the main display.

Nano shortcuts are CTRL+O (Save), CTRL+W (Search), CTRL+X (Quit)

**Comment by alexandrebfaust** [comment]
OOOH YEAH BRO! It's working! :+1: If I restart my pc in live mode, his continue working with this edited file?

**Comment by alexandrebfaust** [comment]
Now the question is: How I connect in a wifi network? :smile:

**Comment by cudencuden** [comment]
http://www.lakka.tv/doc/Network-settings/

**Comment by alexandrebfaust** [comment]
Thanks! :+1: :+1: :+1: :+1:
