### ISSUE TITLE
allow case insensitivity when looking for files referenced from a cue file

### ISSUE THREAD

**Issue by trapexit** [libretro/Lakka#468]
Not an uncommon problem to have CUEs refer to wrongly cased files.

**Comment by sergiobenrocha2** [comment]
Get the .cue from redump

**Comment by trapexit** [comment]
I now realize this is not the correct repo for this request but:

Why complicate the user's life? The change would be rather trivial.

**Comment by Alcaro** [comment]
> The change would be rather trivial.

You sure? Enlighten me. The only method I'm aware of is 'enumerate the directory and check every filename', which is far from trivial.

**Comment by trapexit** [comment]
In what way is `opendir, loop on readdir + case insensitive strcmp, closedir, return actual proper filename` complicated? It's maybe 10 lines of code.

**Comment by sergiobenrocha2** [comment]
Then do it yourself... but I think it's better to keep with standard .cue instead the broken ones

**Comment by trapexit** [comment]
Anyone know where the code lives? I'm happy to do it. 

Those cue files are not broken on Windows, OSX, or FAT filesystems on Linux and simply confuses users given there is no feedback to when something fails.

**Comment by Kivutar** [comment]
Take a look at task_database.c

**Comment by trapexit** [comment]
Thanks. I was expecting the the cue parsing logic to be normalized but it exists in each of the cores. So while changing the database code would allow it to search and index in a case insensitive way each core would need to change to get them to load the files. 

Alternatively perhaps tooling could be created and included to Lakka or retroarch to help discover and fix such issues. Ideally the UI and cores could provide a better error reporting API.
