### ISSUE TITLE
Dell Optiplex GX260 Flickers Flower Screen

### ISSUE THREAD

**Issue by Kaizodude** [libretro/Lakka#471]
So First off, I'm new to within so you'll have to excuse me for not writing in the right manner. 
My issue is the following
My screen keeps flickering the image of the flower. I am using a Dell Optiplex GX260 with 1GB Ram , 20GB HDD and a Intel pentium 4 at 2GHz. 
i have tried looking on the BIOS +really old one+ and no settings changed it. I will post a quick video of the issue

**Comment by Kaizodude** [comment]
https://youtu.be/flnW7jfYkWo

**Comment by gouchi** [comment]
Do you reproduce the issue with [latest nightly](http://mirror.lakka.tv/nightly/Generic.i386/Lakka-Generic.i386-devel-20160811142808-r21565-gc79651a.img.gz) ?

**Comment by Kaizodude** [comment]
Well.. I know it's a nightly build. It's i386 and it was for PC and it was from August 11th 2016

**Comment by Kaizodude** [comment]
So yes. The latest nightly build for 32bit PC
http://sources.lakka.tv/nightly/Generic.i386/

**Comment by Kaizodude** [comment]
Also. As of right now. When I click installer it lags alot. Dosent get past flower

**Comment by gouchi** [comment]
Can you try to boot by adding to [boot arguments](http://wiki.openelec.tv/index.php/Boot_Arguments) (Press Tab to edit cmdline) **textmode** then try to get some [log](http://www.lakka.tv/doc/Troubleshooting-Lakka) ?

Thank you.

**Comment by Kaizodude** [comment]
OK one moment. Wherever I try and boot it does this https://youtu.be/TdbDdPqNoWY
It just sticks at the flower screen, even when I type in the command

**Comment by gouchi** [comment]
Try to add boot arguments for Live Mode.

Can you try to press F12 to access Boot Menu and boot on your USB key ?

**Comment by Kaizodude** [comment]
That's what I've been doing. Sorry for the confusion

**Comment by gouchi** [comment]
Another thing you can try is to boot first with [Plop Boot Manager on CD](https://www.plop.at/en/bootmanager/plpbt.bin.html#runcd) to boot to the usb key.

Maybe it will help.

**Comment by Kaizodude** [comment]
Ok ok hold on. My Dell is lagging alot right now. It's loading 1 line of pixels per second... I don't know what's going on

**Comment by Kaizodude** [comment]
Opps

**Comment by Kaizodude** [comment]
Ah one moment

**Comment by Kaizodude** [comment]
How do I get the logs?
All I see is the blinking flower

**Comment by Kaizodude** [comment]
Location

**Comment by Kaizodude** [comment]
Never mind I found it. I will post a pic

**Comment by Kaizodude** [comment]
Uhg. Sorry for being a pain
 I revoke that nevermind. Where do I find it again?

**Comment by Kaizodude** [comment]
And what are those I things your putting?

**Comment by Kaizodude** [comment]
Ok so I know where to put the commands. It only lets me type the first and third one in. The 2nd crashes it

**Comment by Kaizodude** [comment]
But where's the output file?

**Comment by gouchi** [comment]
Try to come on [IRC](http://webchat.freenode.net/?channels=%23lakkatv) so that other people can also help you with the reference of this [issue](https://github.com/libretro/Lakka/issues/471).

**Comment by Kaizodude** [comment]
No one appears to be online :/

**Comment by gouchi** [comment]
Graphic card (8086:2562) is too old to handle RetroArch with kernel 4.6
