### ISSUE TITLE
Image Viewer / Movieplayer / Mediaplayer

### ISSUE THREAD

**Issue by kuxii2016** [libretro/Lakka#475]
the pack is not in Lakka
https://github.com/libretro/libretro-super/blob/master/dist/info/imageviewer_libretro.info
its Only Pic Viewer,but I understand it

**Comment by gouchi** [comment]
You will have to update [RetroArch commit id](https://github.com/libretro/Lakka/blob/lakka/packages/libretro/retroarch/package.mk#L22) to get history files for music/video/image.

**Comment by Kivutar** [comment]
We will do that later.

**Comment by Kivutar** [comment]
OK those new tabs are available in the latest development builds. There will be a release soon.
