### ISSUE TITLE
Any chance Lakka to be merged with LibreELEC?

### ISSUE THREAD

**Issue by Jimmy-Z** [libretro/Lakka#493]
Both targeting TV, someone else thinks this make sense?

**Comment by Kivutar** [comment]
We're porting Lakka to LibreELEC. But there are some differences in the goals of both projects.

Lakka is very retrocompatibility oriented. We try to support old hardware.

LibreELEC tries to keep a clean codebase and sometimes drops code that we still use.

If we have more time, we will invest ourselves in LibreELEC maintainance and try to keep those part alive, so our "fork" will be easier to rebase.

**Comment by Kivutar** [comment]
I close this for now.
