### ISSUE TITLE
Menu Shader Pipeline degrades.

### ISSUE THREAD

**Issue by wboyo** [libretro/Lakka#494]
Just thought I'd mention it, but if you leave the Lakka frontend running for a day or two the Menu Ribbon (including simplified) degrades and starts looking blocky and jagged, and not as beautiful when it first starts.

:)

**Comment by Kivutar** [comment]
Affects XU3 too.

**Comment by wboyo** [comment]
Sorry, forgot to mention I'm running on PC.

**Comment by Kivutar** [comment]
Also affects the NVIDIA Shield.

What graphic card are you using @wboyo ?

**Comment by Kivutar** [comment]
@bparker06 found a fix for this, it needs to mature a little before we merge it.

**Comment by bparker06** [comment]
The fix has been merged in.
