### ISSUE TITLE
RPi3 bluetooth freeze

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#495]
```
<Zanx> The Rpi3 native BT driver for 4.1 (Sorry is that core? Kernel? :/) causes a system freeze. This is well documented. Upgrading to 4.6 works but I believe a driver patch would fix the issue as well.
<kivutar> ok let me check the kernel version in the last development builds..
<Zanx> I investigated recompiling it but hit a few problems and decided to be patient instead haha.
<Zanx> I DLed Rpi3 stable a few days ago and it was 4.1.
<kivutar> yes, the stable is quite old now
<kivutar> we're still using 4.1
<Zanx> http://lxr.free-electrons.com/diff/drivers/bluetooth/hci_ath.c?v=4.4;diffval=4.1;diffvar=v is a driver comparison
<Zanx> https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=raspberry%20pi%20bluetooth%204.1%20freeze top several links are all relevant for extra diagnostics.
```

**Comment by Kivutar** [comment]
Fixed.

**Comment by Gregwar** [comment]
@Kivutar fixed how?
I experience freezes on my rpi3 using dualshock3 joypad, it is related to this?

**Comment by Kivutar** [comment]
By this commit https://github.com/libretro/Lakka/commit/a0dd7305888c05c105b07e1867336cab2fd04cb3

And I don't exeprience freezes with my DS3

**Comment by Gregwar** [comment]
I am on the 12/12 release img, does it includes this commit?

**Comment by Kivutar** [comment]
Yes

**Comment by Gregwar** [comment]
Ok, so I am still experiencing freezes, and it seems ok when I use wired
joypad
(Rpi3, 12/12 img and dualshock 3)

Looks like it happens more often on more greedy emulators like N64

Le lun. 26 déc. 2016 19:02, Jean-André Santoni <notifications@github.com> a
écrit :

**Comment by Kivutar** [comment]
Ok that could explain it. Do you often see the rainbow square on the top right corner?

**Comment by Gregwar** [comment]
No, never
(I have a 2.5A psu)

I also tried on two boards and two different sd cards (both class 10)

Le lun. 26 déc. 2016 19:12, Jean-André Santoni <notifications@github.com> a
écrit :

**Comment by DeFrenZ** [comment]
I've experienced the same. Disabling "Threaded video" seems to fix it in my case (RPi3 + DS4 for me)... or at least it didn't happen in a while after changing it
