### ISSUE TITLE
License unclear or undefined(?)

### ISSUE THREAD

**Issue by ddxor** [libretro/Lakka#497]
There is no clearly visible software license for Lakka. Which software license is Lakka released under - if any? This information should be made clearer.

**Comment by Kivutar** [comment]
Hello, like for any other linux distro, the license of Lakka is the sum and combination of all the licenses of each individual package included.
You have the full list here: https://github.com/libretro/Lakka/tree/lakka/licenses
And there is also the Non Commercial license of some SNES emulators that applies there.
