### ISSUE TITLE
Implement rpi gpio and wiringpi to Rpi2/3

### ISSUE THREAD

**Issue by xprmntlarcade** [libretro/Lakka#506]
As discussed in forum:
http://libretro.com/forums/showthread.php?t=6453&page=2&p=48932#post48932

Kivutar is willing to enable this feature "rpi GPIO" and "Wiringpi" so we can connect joysticks and buttons directly into the GPIO Rpi2/3.

Thanks!

**Comment by xprmntlarcade** [comment]
HI! 
when could this feature be implemented?
thanks

**Comment by Kivutar** [comment]
OK can you try this image please? http://static.kivutar.me/Lakka-RPi2.arm-devel-20161110230408-r21640-ge218f0f.img.gz

**Comment by xprmntlarcade** [comment]
Great!, is it the same pinout as: http://libretro.com/forums/attachment.php?attachmentid=643&d=1475334429    ?

**Comment by Kivutar** [comment]
I believe so.

**Comment by Kivutar** [comment]
I have not added any daemon listening to the GPIO state to emulate a keyboard or a joypad. I just added wiringPi as well as the gpio command line tool.

**Comment by xprmntlarcade** [comment]
it doesnt seem to be working, but im making contact touching a ground + LEFT with a wire while in the main menu

**Comment by xprmntlarcade** [comment]
Do I need to add the "daemon listening to the GPIO"? If so, how would I do that?
Does this mean this implementation is incomplete? 
Sorry for my ignorance in this matter, I thought it would be working instantly.

**Comment by Kivutar** [comment]
Can you check if the gpio command line tool is working?
