### ISSUE TITLE
Some Games does not work with Raspberry Pi 2

### ISSUE THREAD

**Issue by foxp4v** [libretro/Lakka#518]
Hello, some games like R-type, R-Type II, R-Type Leo does not work with the Raspberry Pi version of Finalburn Alpha, when i start them only a black screen is displayed, other games like Wonder Boy simply crash the emulator. All these games works fine with the Windows version. Thanks for all the grat work.

**Comment by cbluth** [comment]
Please leave more details about the core/platform these games are being run on, and if you can, the md5sum of each game. I am willing to test them out on my RPi2 setup.

**Comment by externo6** [comment]
This is most likely a core issue and not a issue with Lakka.

**Comment by foxp4v** [comment]
Probably it's a core issue, if i remind good also an rertopie with the Final Burn Alpha core there are the same problems, instead with the Mame 2003 core works well. I must open an issue otherwhere then?

**Comment by gouchi** [comment]
Please try to provide some [Lakka system log](http://www.lakka.tv/doc/Troubleshooting-Lakka).

Thank you.

**Comment by Kivutar** [comment]
Are these games in the list of supported games of FBA?

**Comment by Kivutar** [comment]
The games doesn't crash but I get a black screen and RetroArch hangs forever.

**Comment by foxp4v** [comment]
With the latest version of Retropie (4.1), the issue is solved, the latest version of lr-fbalpha has fixes for irem hardware on ARM cpus, also Wonderboy works well now

**Comment by Kivutar** [comment]
OK I will update lr-fbalpha then.
