### ISSUE TITLE
Incorrect arch update from the GUI

### ISSUE THREAD

**Issue by syepes** [libretro/Lakka#527]
Hello,

I have just noticed that from the GUI "Online Updater ->Update Lakka" is downloading a tar file does not correspond to the currently running arch.

Example:
I am running Lakka-imx6.cuboxi.arm-devel-20161106233514-r21640-ge218f0f.tar
And then running the updater it downloads: Lakka-imx6.udoo.arm-devel-20161106233744-r21640-ge218f0f.tar

Am I missing something?

**Comment by oblitum** [comment]
Same happened from me.

**Comment by Kivutar** [comment]
OK I will try to fix that.
