### ISSUE TITLE
lakka-update bricks devices

### ISSUE THREAD

**Issue by oblitum** [libretro/Lakka#529]
First I've run the updater from UI and got #527, still, I thought it would be some compatible image anyway. The updater just reaches 20% and then go back to 0%. I've wait for it to do that 5 times before rebooting. After the 5th time I've rebooted from ssh. On boot it still found a tar file, but md5 failed, so it booted normally.

I've then tried lakka-update from ssh. It didn't display which image it was downloading. On boot the device found a correctly downloaded tar now. It updated the system, and now the system doesn't boot anymore.

**Comment by oblitum** [comment]
I'm on a Cubox-i 4x4.

**Comment by syepes** [comment]
@oblitum Watchout the lakka-update also has an issue, it does not download the last version.
You should change this on the lakka-update script:
`PROJECT=imx6 -> PROJECT=imx6.cuboxi`
