### ISSUE TITLE
Latest Nightly drops SMB

### ISSUE THREAD

**Issue by maxengel** [libretro/Lakka#546]
I installed the latest nightly (Lakka-RPi2.arm-devel-20161128021958-r21681-gb8cc538.img.gz), and Samba is no longer showing up, despite verifying that it is exposed in the menu. Power cycling the RPi3 has not made a difference.

**Comment by Chocobobobo** [comment]
Had the same problem, but after "upgrading" (see issue #543), it eventually came back after a few reboots, out of the blue.

**Comment by Chocobobobo** [comment]
Just compiled the latest version (47d00aa) and it works fine. Tested on RPi3.

**Comment by Kivutar** [comment]
Works fine for me too, tested this morning with the last version.
