### ISSUE TITLE
Xbox One wired pad is not working on Raspberry Pi 2

### ISSUE THREAD

**Issue by tomjal** [libretro/Lakka#551]
I connected Xbox One wired pad to Raspberry PI 2 and Lakka can recognizes it as Xbox One pad but nothing is working and Xbox logo on pad is not light up.

I found out that Xbox One Controller for Windows.cfg config file has different PID than mine (its 767 there while mine is 721), how can i change it?

**Comment by Helinos** [comment]
I have the same issue with the controller but I'm new to this and don't know what Windows.cfg is

**Comment by tomjal** [comment]
I installed newest nightly version and gamepad is till not working, so I gave up and tried RetroPie. In RetroPie there is no problem, everything works.

**Comment by Kivutar** [comment]
I don't get it, mine works well

**Comment by tomjal** [comment]
I will try to find out what is wrong, but currently have no time for that so i think the issue can be closed.
