### ISSUE TITLE
Adding reicast to XU4 builds

### ISSUE THREAD

**Issue by Arnochocobo** [libretro/Lakka#564]
Salut Kivutar! J'espere que tout va bien.

Just received my XU4 today, and I love that thing. Not sure why everyone is complaining about 2D tearing because of Mali drivers issues, but Lakka works great on it. 
I have seen this video:
https://www.youtube.com/watch?v=9_LxdO-auP4

Apparently the XU4 has enough horsepower to run Reicast, so I was wondering if you could add it to the XU4 builds?

Thanks!

**Comment by Kivutar** [comment]
Hello Arnochocobo,

ça va et toi ?

reicast-libretro is not yet copatible with arm. But it will be in the future. I close this for now :)

**Comment by Arnochocobo** [comment]
Ca va plutot bien. Leur video est un fake? Depuis le Japon, impossible pour moi de recup la derniere image en un seul morceau et de tester moi-meme, merci Free... Tu peux essayer de jeter un oeil? http://recalbox.remix.free.fr/

**Comment by Arnochocobo** [comment]
More and more videos, some people managed to get it working on XU4

https://www.youtube.com/watch?v=VYMisZM18jk

**Comment by Kivutar** [comment]
They are not using the libretro version of reicast but the standalone version. In lakka we wait until the libretro team does the port and then we package the core. So we keep things clean with only one configuration file for all the emulators.

**Comment by Arnochocobo** [comment]
Understood, merci pour les precisions.
