### ISSUE TITLE
Browsing through big playlists with screenshots crash RPi3

### ISSUE THREAD

**Issue by killer101** [libretro/Lakka#577]
While browsing through big playlists, Lakka crashes after a certain amount of moves and only showing black screenshots after that. Restarting Retroarch solves the problem. This bug is reproducible.

**Comment by gouchi** [comment]
Duplicate of #262 which has been reported in [RetroArch issue tracker](https://github.com/libretro/RetroArch/issues/2791).

**Comment by Kivutar** [comment]
Yes, I close this one. It affects more platforms than just the RPi
