### ISSUE TITLE
update keyboard navigation instructions in FAQ

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka#580]
The FAQ refers to the prior keyboard navigation scheme: 
"How do you navigate with a keyboard?
Use the directional arrows, and X and W keys."

Rather than X and W, the FAQ should state that Enter and Backspace are used for navigation.

Direct link: https://github.com/libretro/Lakka/wiki/FAQ#how-do-you-navigate-with-a-keyboard

**Comment by gouchi** [comment]
Thank you I updated the [FAQ](https://github.com/libretro/Lakka/wiki/FAQ#how-do-you-navigate-with-a-keyboard).
