### ISSUE TITLE
guidelines for contributing to Lakka repo point to OpenElec material

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka#581]
When creating a new issue in the Lakka github repository, a prominent link instructs the user to "Please review the guidelines for contributing to this repository."

Clicking on this link takes the user to content that seems to be directly copied from the OpenElec source:
https://github.com/libretro/Lakka/blob/lakka/CONTRIBUTING.md

Screenshot:
![openelec-contribution-instructions](https://cloud.githubusercontent.com/assets/19554678/21340040/d95ccb26-c651-11e6-84f2-003960026b4f.png)

**Comment by gouchi** [comment]
It seems we should add [ISSUE_TEMPLATE.md](https://github.com/blog/2111-issue-and-pull-request-templates) file in the repository.

**Comment by markwkidd** [comment]
PR that addresses the "CONTRIBUTING" document: https://github.com/libretro/Lakka/pull/619

Another PR might be a good idea to add the ISSUE_TEMPLATE.md as mentioned in https://github.com/libretro/Lakka/issues/581#issuecomment-268335510

**Comment by markwkidd** [comment]
A second PR to address the ISSUE_TEMPLATE idea: https://github.com/libretro/Lakka/pull/620
