### ISSUE TITLE
Lakka on TVbox MXQ s805

### ISSUE THREAD

**Issue by germinbmxer** [libretro/Lakka#589]
Hello all! I'm Brazilian and don't write english very well, but I will try to explain the issue.
I'm trying to run lakka on TVbox MXQ S805 (the hardware is very similar to Odroid C1), but I don't have much knowledge.
Ok, I booted the system using Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf.img by putting manual commands to test like fatload, bootm, etc, and using DTB file of TVbox because DTB of Odroid on this image doesn't work. The system starts, work pretty well, connect on wifi, etc, but after 10 minutes +/- the display turn in Black image like a suspend mode, but the game is running normally(because I hear the sounds in the game like Background music and when I do commands on joystick like a jump, etc). This problem occur in any situation, playing the game or in lakka's menu. Not problem of temperature, because i put a dissipator and the CPU temp is around 38 degree C. No problem on the board because I tried with another one. I don't know why the video image disappear.

 I tried to use a new image file to create my SDcard. After this version(Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf) the systems doesn't boot!  The system expand, restart and start to boot, but the TV stops with Lakka Logo. 
The messages on serial stops in:

[  OK  ] Started Avahi Daemon.
[  OK  ] Stopped Udevil mount service.
[  OK  ] Stopped Udevil mount service.
[  OK  ] Created slice system-udevil\x2dmount.slice.
         Starting Udevil mount service...
         Starting Udevil mount service...
[  OK  ] Reached target Sound Card.
         Starting Samba NMB Daemon...
[  OK  ] Started RPC bind service.
[  OK  ] Started Samba NMB Daemon.
[  OK  ] Stopped Samba SMB Daemon.
         Starting Samba configfile writer...
         Starting WPA supplicant...
[  OK  ] Started Samba configfile writer.
         Starting Samba SMB Daemon...
[  OK  ] Started Samba SMB Daemon.
[  OK  ] Started Udevil mount service.
[  OK  ] Started Udevil mount service.
[  OK  ] Started WPA supplicant.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting RetroArch user autostart script...
[  OK  ] Started RetroArch user autostart script.
         Starting Retroarch...
[  OK  ] Started Retroarch.
[  OK  ] Reached target Retroarch.

and nothing happens! The Lakka logo stays on TV:
![logo](https://cloud.githubusercontent.com/assets/24719752/21457401/3f398a4e-c916-11e6-9ba8-f56cdc7692b6.jpg)

I edited the bootargs to display console on laka using "Ctrl+Alt+F3" and do this command like described on Lakka page:
`systemctl stop retroarch.service; retroarch -v`

and system returns this, but I don't know how to solve:
![error](https://cloud.githubusercontent.com/assets/24719752/21456573/2bf1d492-c910-11e6-92f6-7256f14d3ea2.jpg)

All images after "Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf.img" do the same screns!
The complete serial boot is present here:
[https://drive.google.com/open?id=1ov4SvGVdCOK3BNIcX2IseCg69URJPTbXPPG_EE6RIzQ](url)
Thank'you.

**Comment by Kivutar** [comment]
Hi, the C1 image is not similar enough to run on your MXQ. Wait for the S805 port of lakka to be finished.

**Comment by germinbmxer** [comment]
Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf.img work on MXQ, but after 10 minutes the screen goes turn off

**Comment by Kivutar** [comment]
Is the menu displaying before that?

**Comment by germinbmxer** [comment]
lakka's menu?
With this image, the system work normally, i play the game normally, but after +/-10 minutes th screen goes off, but sound and commands are working (I know because the sounds, but the sreen doesn' return)

**Comment by germinbmxer** [comment]
As you can see, Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf.img is running normally on MXQ without any mod. But after a time, screen turn black.
![img1](https://cloud.githubusercontent.com/assets/24719752/21468527/5bfc01a0-c9f4-11e6-8e5a-5ff937468df7.jpg)
![img2](https://cloud.githubusercontent.com/assets/24719752/21468533/8e0f3c52-c9f4-11e6-9334-0ed78725ee8f.jpg)

**Comment by germinbmxer** [comment]
The time is exactly 10 minutes! I think that has a "suspend screen" or "screensaver" activated.

**Comment by germinbmxer** [comment]
I made some new tests. If I maintained a USB keyboard plugged, when screens goes off, I press some key in keyboard and screens returns!

**Comment by Kivutar** [comment]
you need to add a consoleblank=0 in the cmdline maybe

**Comment by germinbmxer** [comment]
Worked! Thank you. I add `consoleblank=0` on cmdline like you described.
Now, I using Lakka-OdroidC1.arm-devel-20161002115148-r21593-g03241bf.img with another DTB archive in MXQ tv box running perfect. I tried to update to last one, but appear message md5 error :(
But for me, is ok to run this version.

**Comment by Kivutar** [comment]
Ok good to know. Any idea if your box is one of these?

    HD18Q  m201d  MK808B.Plus  MXQ

**Comment by germinbmxer** [comment]
I don't know what my box, but .dtb file of all of these versions boot here normaly(only with OdroidC1.arm-devel-20161002115148  or old versions before this):
`meson8b_hd180.dtb` `meson8b_mk808.dtb` `meson8b_mxq.dtb` `meson8b_m201.dtb`
I only need to rename files to `meson8b_odroidc.dtb` and replace in SDcard.

**Comment by germinbmxer** [comment]
if you need to see these files, i put here:
[https://drive.google.com/open?id=0B-kAdjgbtkY6VzFmdnY4eE9jQXc](url)

**Comment by germinbmxer** [comment]
I found this image: [static.kivutar.me/Lakka-S805.arm-devel-20161129115602-r21683-gb135373.img.gz](http://static.kivutar.me/Lakka-S805.arm-devel-20161129115602-r21683-gb135373.img.gz)

It working too

**Comment by Kivutar** [comment]
Yeah it's the image we are currently working on. So you have an HD18Q like me.

**Comment by germinbmxer** [comment]
Nice notice. :)
will you create instalation to NAND?

**Comment by olekhov** [comment]
Greetings, I'd like to get involved.
I've got MXQ clone, black square box 11.5x11.5cm with red-blue LED and MXq label.
Rear connectors: 
USB-4
SPDIF
AV (with button accessible with a match or toothpick through the jack hole)
HDMI
Ethernet
Power connector 5v barrel

Boot logo says i'ts MXQ HD18Q mbox  v2
![img_20170118_100243](https://cloud.githubusercontent.com/assets/2698890/22054497/eb16c67e-dd66-11e6-81d6-0dffa4a2e58b.jpg)

wifi chip is Realtek RTL8188ETV

motherboard says it's v1.1

The core board has an UART, how convenient; soldered a header there. UART is 115200 8N1
![img_20170118_091623](https://cloud.githubusercontent.com/assets/2698890/22053596/c3be292c-dd62-11e6-8dfe-98b368df0e0b.jpg)

Jumped to UBoot shell, some logs are attached.

[uboot.txt](https://github.com/libretro/Lakka/files/713218/uboot.txt)
[mmcinfo.txt](https://github.com/libretro/Lakka/files/713219/mmcinfo.txt)
[env.txt](https://github.com/libretro/Lakka/files/713220/env.txt)

Tried to manually boot r21683 image from previous comments. The boot process starts normally, but then ends up complaining missing /flash/SYSTEM
[boot.txt](https://github.com/libretro/Lakka/files/713221/boot.txt)
![img_20170118_100415](https://cloud.githubusercontent.com/assets/2698890/22054561/3f5d1cb0-dd67-11e6-9a70-11039b2d4051.jpg)

It's a pity that serial console is disabled. Hooked USB keyboard and got some access to system.
![img_20170118_100629](https://cloud.githubusercontent.com/assets/2698890/22054567/45e2a38e-dd67-11e6-8ef3-9506f583057a.jpg)

How to properly boot Lakka?

I'd like to get dualboot with Android, if the SD with Lakka is missing. I think some twiddling with "preboot" or "recovery" uboot environment vars will do the trick.

**Comment by Kivutar** [comment]
It's just an HD18Q, we support it, try this image http://static.kivutar.me/Lakka-S805.arm-devel-20161129115602-r21683-gb135373.img.gz
