### ISSUE TITLE
Neo Geo screenshots not displayed at all

### ISSUE THREAD

**Issue by killer101** [libretro/Lakka#593]
Hi! All my screenshots for all other systems are displayed without any problem. The Neo Geo (Tab) want display screenshots at all. I named all of them to the playlist names. Nothing at all. Any tricks to do so, or just a bug!?

**Comment by Kivutar** [comment]
Hi, we don't have a Neo Geo tab in lakka, but we have a tab for FBA

**Comment by killer101** [comment]
Interesting! So why do I have one? I made a playlist for Neo Geo. The Controller Symbol is shown correct as tab. The Thumbnail Updater has a package for it. Everything is running smooth except the screenshots. Any reason for this?

**Comment by Kivutar** [comment]
Try to enable GPU screenshots in the video settings?

**Comment by markwkidd** [comment]
@killer101 there are currently no screenshots for Neo Geo in the thumbnail repository, just boxart.

You can probably copy the correct screenshots from the MAME thumbnail set into the Neo Geo folder on your Lakka installation (by creating a folder called Named_Snaps) in order for them to appear.

You could also try to use the AHK Arcade Playlist and Thumbnail script to download just the correct Neo Geo snaps and title screens if you have access to a Windows PC and some time on your hands: https://libretro.com/forums/showthread.php?t=7802

**Comment by killer101** [comment]
I have my own screenshots and everything else set up for the Neo Geo tab. Lakka isn't just displaying them. They work perfectly if I put them to the FBA tab!

**Comment by Kivutar** [comment]
Show me the path of your Neo Geo screenshots?

**Comment by killer101** [comment]
I use "SNK - Neo Geo" ... "Named_Snaps". Like the one the Thumbnailupdater creates.

**Comment by Kivutar** [comment]
And is your tab also named "SNK - Neo Geo"?

**Comment by Kivutar** [comment]
In our RDB, I see no SNK - Neo Geo https://github.com/libretro/libretro-database/tree/master/rdb

**Comment by killer101** [comment]
No, the tab is just named "Neo Geo". The rom symbols are CDs. The Thumbnail Updater is providing material for "SNK - Neo Geo". You are right about the rdb. I think something is messed up here. ...Maybe Lakka can provide a seperate tab for Neo Geo in the future. I like to have the roms seperated from the FBA stuff?!

**Comment by killer101** [comment]
No, if you do so you end up in a tab without symbols. Just black squares!
But I found the solution ...
The name of the lpl has to be "Neo Geo.lpl", also inside the playlist. Example attached at the end!
The name of the thumbnail dir has to be "Neo Geo" too.
Now you get a controller symbol, rom symbols and the games are working. Maybe we have an unoffical Neo Geo tab now. Looks good, runs fine, works for me!

Maybe this tab was officially reserved for the "Neo Geo CD System" as it shows CDs as rom symbols?!

Here's the example ...

/storage/roms/neogeo/blazstar.zip
Blazing Star
/tmp/cores/fbalpha_libretro.so
FB Alpha
DETECT
Neo Geo.lpl
