### ISSUE TITLE
FBA samples folder

### ISSUE THREAD

**Issue by killer101** [libretro/Lakka#597]
Can't get FBA to find the relating samples to the roms? Where do the samples folder have to go to?

**Comment by shakkalakka** [comment]
i have the samples(*.zip) stored in "./system/fba"
(the "fba"-folder have to created at first)

dont know exactly but it seems to work

**Comment by killer101** [comment]
Thanks, works perfect!

**Comment by killer101** [comment]
Maybe someone can put this info to the docs. I think a lot more people are interested.

**Comment by hericstrada** [comment]
Sorry, but, what is those samples?

**Comment by shakkalakka** [comment]
the samples are mostly additional audio-files for a few acade-games. Some original PCBs uses "real audio" instead of "chiptunes" (as i understand it)

**Comment by juri74** [comment]
hello thanks very much!!
i didn't know about that, so is the final path "storage/system/fba/samples/"? (and "storage/system/mame2003/samples/"? for mame2003?) all lowercase?
one question can i have both FBA and MAME2003 collections? does they appear in different list or one big list in lakka menu?
thanks again!

**Comment by shakkalakka** [comment]
hello,
**"storage/system/fba/samples/**? (?=*.zip) 
and 
**"storage/system/mame2003/samples/**? (?=*.zip)
are the right paths.

Mame2003 and FBA Files are shown as seperate Playlists. The PL for FBA can be generated by lakka. 
for mame2003 you have to use a 3rd Party Playlist Generator (i recommend markwkidd's "AHK RetroArch Arcade Playlist and Thumbnail Generator").

**Comment by Kivutar** [comment]
So can we close this?

**Comment by killer101** [comment]
Yep, think so!
