### ISSUE TITLE
update for "Playlists" documentation

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka#604]
Since December (https://github.com/libretro/RetroArch/pull/4183) , RetroArch can now process manually-created playlists with either Unix endlines or Windows endlines. That means that the Playlists documentation could use an update: http://www.lakka.tv/doc/Playlists/

I would like to suggest that the section labelled "Playlist File Format" be changed to start off with:

> Each playlist is a plain text file, and each entry in a playlist must be composed of 6 lines.

The current text says:

> Each playlist is a plain text file (with Unix-style newlines) and the .lpl extension. Each entry in a playlist must be composed of 6 lines.
> 
> Warning: If you are creating a playlist file on a Windows PC, please take care to ensure that the playlist file is in Unix format. Notepad, the text editor included with Windows, does not support Unix format. Notepad++ is one free Windows editor that can create Unix text files and convert existing files to Unix format.

**Comment by gouchi** [comment]
Thank you, I [updated the wiki](https://github.com/libretro/Lakka/wiki/Playlists/_history).
