### ISSUE TITLE
Lakka menu is too slow 

### ISSUE THREAD

**Issue by Anunknownentity** [libretro/Lakka#605]

**Comment by Anunknownentity** [comment]
So I have an old Dell inspiron b130 laptop that I want to play games with. But after the flower screen the menu is so laggy I cant navigate through the settings to lower the resolution. So my question is, isn;t there a way to change the settings to the lowest before boot up so I can navigate through the menu? If not what can you suggest I do?

PS: b130 cant upgrade gpu, it can only upgrade ram and proccesor ( Will both of this help?)

Plz help me because I have no other uses for that laptop

**Comment by gouchi** [comment]
Try to [disable ribbon](http://www.lakka.tv/doc/FAQ/#menu-xmb-is-too-slow), if it is not enough try to change menu driver to rgui (menu_driver = "rgui").

You will have to edit the [configuration manually](http://www.lakka.tv/doc/Configuring-Lakka).

**Comment by Arnochocobo** [comment]
Feel free to purchase something not being 23 years old, that might help too.

**Comment by Kivutar** [comment]
Disabling the ribbon will certainly fix your problem.

It uses some functions not present in some video drivers.
