### ISSUE TITLE
Documentation: update PC-FX BIOS info

### ISSUE THREAD

**Issue by markwkidd** [libretro/Lakka#612]
Due to a minor error in porting from standalone Mednafen to libretro, the PC-FX core was looking for the wrong BIOS filename -- it should be **pcfx.rom** instead of pcfx.bios. This has been corrected as of today's PR: https://github.com/libretro/beetle-pcfx-libretro/pull/15

This means that the Lakka BIOS information will need to be updated by whenever the updated PC-FX core is built in. The filename should be pcfx.rom and the updated hash information is available here: https://github.com/libretro/libretro-database/blob/master/dat/BIOS%20-%20Merged.dat#L47

Thank you!

**Comment by Kivutar** [comment]
I updated the doc here https://github.com/libretro/Lakka/wiki/BIOSes

Thanks
