### ISSUE TITLE
Problem with asrock j3455-itx

### ISSUE THREAD

**Issue by hackbird001** [libretro/Lakka#627]
Hello,

i installed both version 32/64 from the main on USB.
With both version boot hangs on the flower. Nothing happens.

My Board: Asrock J3455-ITX
Sound Card: Realtek ALC892
Graphics Card: Integrated Intel® HD Graphics 500: 12 EUs inside (Up to 750MHz)

**Comment by gouchi** [comment]
Some [questions](https://github.com/libretro/Lakka/blob/lakka/ISSUE_TEMPLATE.md) haven't been answered ;-)

Which version of Lakka are you using ? Moreover, is it possible to get some [lakka system logs](http://www.lakka.tv/doc/Troubleshooting-Lakka) ?

Thank you.

**Comment by hackbird001** [comment]
Hey, i used both version from the offical main page (lakka.tv)...
Log cannot post because it hangs on flover bootscreen

**Comment by gouchi** [comment]
Please try to connect by [ssh](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/#ssh) or [direct access](http://www.lakka.tv/doc/Accessing-Lakka-command-line-interface/#direct-access).

Thank you.

**Comment by hackbird001** [comment]
direct access wont work.
How are the login?
I know u must use putty and my ip adress from htpc but password and so on?

**Comment by gouchi** [comment]
If you can't ssh, you should have succeeded with direct access. 

Can you try to append to the cmdline 
`nosplash textmode`

It should disable the splash screen while booting and boot to a terminal.

**Comment by hackbird001** [comment]
Hey gouchi,

never done before. 
Can u explain me how i should do this??

**Comment by gouchi** [comment]
Please read [this documentation](http://www.lakka.tv/doc/The-bootloader/#on-generic-pc).

**Comment by hackbird001** [comment]
Hey gouchi,

wont work. did hangs on the flower bootscreen.

First i was type tab then it comes the cmd line with "kernel version text and so on" after this i type: nosplash textmode.....   Hangs on flower

Second i delete all the text and write again nosplash textmode.   Hangs again

**Comment by gouchi** [comment]
Strange. Can you try to make a test with  [Lakke LE](http://le.builds.lakka.tv/Generic.x86_64/) (LibreELEC based) and select Run mode, if you reproduce the issue ?

Thank you

**Comment by gouchi** [comment]
Strange it should have disable the splash screen. Can you try to append to the cmdline 
`debugging`

Thank you.
