### ISSUE TITLE
About Asus Tinker Board

### ISSUE THREAD

**Issue by FelipeBR2** [libretro/Lakka#632]
I was browsing today when I found [this](https://www.f3nws.com/news/the-asus-tinker-board-is-a-powerful-raspberry-pi-rival-that-plays-4k-video-srPbJC).

I though it's specs looked nice, and was thinking about buying one.

What are your thoughts on this board? Do you think it will fully support lakka?

**Comment by Kivutar** [comment]
Hi. No Lakka can't run on Rockship

**Comment by Unadan** [comment]
Never?
