### ISSUE TITLE
Dual boot partition

### ISSUE THREAD

**Issue by dabit1** [libretro/Lakka#649]
Hi!

I'm trying to install Lakka and Kodi in the same PC. I did two primary partitions but when I try to install Lakka it removes all disk, is there any way to install it in a partition?

Many thanks!

**Comment by Kivutar** [comment]
Hello,

Dual boot works, you can find some documentation on the web on how to dualboot OpenELEC or LibreELEC.

But you have to do it manually. There are no *user friendly* way to do this in Lakka and it's a feature that we don't want to support yet.
