### ISSUE TITLE
Underscore

### ISSUE THREAD

**Issue by evil666** [libretro/Lakka#653]
In the WiFi settings when entering your password. The underscore "_" seems to be missing. Only way I got it on WiFi was to connect a cord, ssh into it and use connmanctl.

**Comment by Kivutar** [comment]
I just pushed a commit on RetroArch that adds a full symbol page on the OSK. This bug will be fixed with the next RetroArch update, in about a month. So I close this issue for now.
https://github.com/libretro/RetroArch/commit/e587264b3de4f8d6de9db83eb7861a79738ac8c2
