### ISSUE TITLE
Feature Request - Combine Multi-disk Games

### ISSUE THREAD

**Issue by omega9380** [libretro/Lakka#659]
Would there be a way to combine multi-file games into one entry in the playlist?  IE, Final Fantasy VII for the PSX is 3 disks, and of course lists 3 entries in the playlist.  Maybe for multi-disc games, have the name of the game pop open a sub menu listing the various disks in the set.  Just an idea!  Thanks and keep up the good work!!

**Comment by jeapostrophe** [comment]
This belongs on the retroarch repo. I just reposted it for you --- https://github.com/libretro/RetroArch/issues/4755

You should close this issue.

**Comment by omega9380** [comment]
Cool!  Thanks!
