### ISSUE TITLE
Systematic theme not showing up in Lakka

### ISSUE THREAD

**Issue by TWOTALL4UFOOL** [libretro/Lakka#671]
I've been using Lakka and I don't see the Systematic theme. I've seen the folder in the xmb folder. Anyway on how to install it?

**Comment by Kivutar** [comment]
Hello, the builds from the website will soon be replaces with builds here http://le.builds.lakka.tv/ that are more recent. Switch to these builds to have systematic.

**Comment by TWOTALL4UFOOL** [comment]
Thank you! I got it installed and it looks sweet.
