### ISSUE TITLE
Black icons mainmenu, wetek core

### ISSUE THREAD

**Issue by batserra** [libretro/Lakka#683]
The issue tracker has moved to https://github.com/libretro/Lakka-LibreELEC/issues
![1495991639154-1043013394](https://cloud.githubusercontent.com/assets/3428433/26530676/d8e03f38-43d9-11e7-83fc-8641f2d52d08.jpg)

Hi i have download latest versión 2.0 for my wetek core but after install all icons are Black, how i can fix it? thanks for all

**Comment by Kivutar** [comment]
fixed
