### ISSUE TITLE
Provide updates

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#72]
OpenELEC uses an XBMC addon to check if updates are available, and if it is the case, they download the files to /storage/.updates.

See this https://github.com/OpenELEC/service.openelec.settings

We don't use XBMC, so we can do it our way. Either we integrate it to RetroArch and our menu, either we implement it as a systemd service.

**Comment by julianxhokaxhiu** [comment]
I Agree. I don't know if the current menu that is there on Lakka works already, but in my case not. I'm using it on a RPI2

**Comment by Kivutar** [comment]
Starting from the latest nightly build, it should start working.

In the Online Updater, you should see a list of all Lakka build. Hitting OK on one of them will download the tar to the .update folder.

Then, rebooting will do the upgrade during the boot.

**Comment by julianxhokaxhiu** [comment]
Perfect, I didn't try it since I updated by hand. This evening I'll take a look at this :) thanks twice!

**Comment by julianxhokaxhiu** [comment]
I tryed it on my RPi2 to update using the menu and I still have the same behavior: I press A then the screen flashes for a second, then I get a broken menu visually. The same applies for `Update Core` menu.

Any hint?

**Comment by Kivutar** [comment]
It happens sometimes when downloading the core list or the update list takes too much time. It can also happen if the url of the core updater is missing in your retroarch.cfg.

Try to delete your retroarch.cfg, so it will be replaced by the one in /etc. (don't forget to stop retroarch service when you do that)

It should fix this problem.

On a fresh install, it should not happen.

**Comment by julianxhokaxhiu** [comment]
Ok, I'll try it this evening :) Thanks

**Comment by julianxhokaxhiu** [comment]
I confirm that I can see the menu list now, I just had the old retroarch.cfg file :) Although the Core updates seems not to work. When extracting it gives an error.

**Comment by Kivutar** [comment]
Yes, that is another bug ahah.
