### ISSUE TITLE
Allow easy WiFi and Network configuration

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#81]
Use the functions here, https://github.com/Niouby/Lakka/blob/941532f7d86dae7f191d21d7dff6749365a44ba3/packages/network/connman/init.d/21_network
Or enable __connmanctl__

**Comment by ProfessorKaos64** [comment]
Anu update on this? I use wifi adapter specifically for Pi devices and works out of the box, but I am unsure how to get this working on the latest image for pi2

**Comment by wraybowling** [comment]
Count me in on this. I have a pi2 with an Edimax wifi usb adapter; likely the most common usb adapter among raspberry pi owners. http://www.amazon.com/Edimax-EW-7811Un-150Mbps-Raspberry-Supports/dp/B003MTTJOY

**Comment by Kivutar** [comment]
Done in the development builds
