### ISSUE TITLE
Udevil + Lakka menu troubles: Filter devices ?

### ISSUE THREAD

**Issue by floreal** [libretro/Lakka#97]
I found out that by default udevil mount ALL devices even on computer startup. As Lakka menu driver will look for every /sroage/roms subdirectories, when i have a *Lot* of big device, then it will take ages blocking the wole system searching everything. Beside I think it is not safe.
1. Is it possible to disable mounting all device on startup, and just detect hotplugs?
2. Is it possible to blacklist devices in writable configuration?

**Comment by Kivutar** [comment]
We could set the mountpoint outside the ROM directory, and let the user change the path himself. It would give the user more control, would fix this bug, and would also prevent the whole external drive to be served in SAMBA shares twice.

**Comment by Kivutar** [comment]
Fixed by 52950c8
